# @package cv
_target_: src.cv.cpcv.SimpleCombinatorialPurgedKFold
n_splits: ${period.n_splits}
n_test_splits: ${period.n_test_chunks}
train_start_date: ${period.train_start_date}
test_start_date: ${period.test_start_date}