# @package cv
train_start_date: ${period.train_start_date}
valid_start_date: ${period.valid_start_date}
test_start_date: ${period.test_start_date}
n_splits: ${period.n_splits}
purge_days: ${period.purge_days}         # 追記: period設定から渡す
embargo_days: ${period.embargo_days}     # 追記: period設定から渡す
