name: "all"
cat_cols:
 - EVT_IsMissingEPS_RAW
 - GOV_MarketSegment_RAW
 - GOV_Sector33Code_RAW
 - SEA_DayOfMonth_RAW
 - SEA_DayOfWeek_RAW
 - SEA_IsGotobi_RAW
 - SEA_IsMonthEnd_RAW
 - SEA_Quarter_RAW
 - SEA_IsQuarterEnd_RAW
