name: str_mdd
feature_cols:
 - BET_Beta60_CSR
 - BET_Beta60_RAW
 - BET_MarketHV20_TSR_252D
 - BET_SectorRelStrength60_CSR
 - BET_SectorRelStrength60_CSZ
 - BET_SectorRelStrength60_RAW
 - CON_RevisionRate_CSR
 - CON_RevisionRate_CSZ
 - CON_RevisionRate_SNZ
 - EVT_IsMissingEPS_CSR
 - EVT_IsMissingEPS_CSZ
 - GOV_MarketSegment_RAW
 - LIQ_TurnoverRatio_CSZ
 - MOM_DistHigh250_CSR
 - MOM_DistSMA75_RAW
 - MOM_High52wDist_CSR
 - MOM_MADev200_CSR
 - MOM_MADev200_RAW
 - MOM_MADev200_SNZ
 - MOM_MADev75_RAW
 - MOM_Momentum12-1_CSR
 - MOM_Return12m_CSR
 - MOM_Return12m_CSZ
 - MOM_Return6m_CSR
 - MOM_Return6m_CSZ
 - QLT_EquityRatio_RAW
 - SEA_DayOfMonth_RAW
 - SPD_OverseaFlowTrend_RAW
 - SPD_OverseaFlowTrend_TSR_252D
 - SPD_VWAPDev_CSZ
 - VAL_EarningsYield_CSR
 - VAL_EarningsYield_CSZ
 - VAL_EarningsYield_RAW
 - VAL_LogPBR_CSR
 - VAL_LogPBR_CSZ
 - VAL_LogPBR_RAW
 - VOL_ATRRatio_CSR
 - VOL_ATRRatio_CSZ
 - VOL_DownsideDev60_CSR
 - VOL_DownsideDev60_CSZ
 - VOL_HistVol20_TSR_252D
 - VOL_HV30_CSR
 - VOL_LargeMoveCount_CSR
 - VOL_LargeMoveCount_CSZ
 - VOL_Volatility60_CSR
 - VOL_Volatility60_CSZ
 - VOL_VolatilityParkinson_CSR
 - VOL_VolatilityParkinson_CSZ
cat_cols:
 - GOV_MarketSegment_RAW