
feature_cols:
  - BET_Beta60_CSR
  - BET_Beta60_CSZ
  - BET_RelSectorReturn5d_CSZ
  - BET_RS25_CSZ
  - BET_RS25_TSR_252D
  - BET_SectorMomentum5d_SNZ
  - BET_SectorRelStrength60_CSZ
  - BET_SectorRelStrength60_TSR_252D
  - CON_RevisionRate_CSR
  - CON_RevisionRate_CSZ
  - CON_RevisionRate_SNZ
  - EVT_IsMissingEPS_RAW
  - EVT_LogDaysSincePub_CSR
  - EVT_LogDaysSincePub_CSZ
  - LIQ_AmihudIlliq_CSZ
  - LIQ_VolumeLog_CSZ
  - MOM_DistHigh250_CSR
  - MOM_DistSMA25-75_TSR_252D
  - MOM_DistSMA25-75_TSZ_20D
  - MOM_High52wDist_SNZ
  - MOM_MACDHistNorm_SNZ
  - MOM_MADev75_SNZ
  - MOM_Momentum12-1_TSR_252D
  - MOM_Momentum12-1_TSZ_20D
  - MOM_NewHighFlag3_TSR_252D
  - MOM_PricePos120_SNZ
  - MOM_RCI26_SNZ
  - MOM_RCI52_CSR
  - MOM_RCI52_CSZ
  - MOM_RCI52_TSR_252D
  - MOM_Return12m_TSR_252D
  - QLT_Accruals_TSR_252D
  - QLT_OperatingProfitGrowthYOY_CSR
  - QLT_OPMargin_TSR_252D
  - QLT_ROA_TSR_252D
  - QLT_SalesGrowthYOY_TSZ_20D
  - SEA_DayOfMonth_RAW
  - SEA_MonthInQuarter_RAW
  - SIZ_LogMarketCap_CSZ
  - SPD_FlowAccel_CSR
  - SPD_FlowAccel_CSZ
  - SPD_MarginRatio_CSR
  - SPD_MarginRatio_CSZ
  - SPD_MarketForeignBuy_TSR_252D
  - SPD_MarketIndividualBuy_TSR_252D
  - SPD_OverseaFlowTrend_CSZ
  - SPD_VWAPDev_CSR
  - SPD_VWAPDev_CSZ
  - VAL_EarningsYield_SNZ
  - VAL_LogPBR_TSR_252D
  - VOL_ATRRatio_CSR
  - VOL_DownsideDev60_CSR
  - VOL_DownsideDev60_CSZ
  - VOL_DownsideDev60_TSR_252D
  - VOL_HV30_CSR
  - VOL_HV30_CSZ
  - VOL_HV30_TSR_252D
  - VOL_HVSlope_CSR
  - VOL_HVSlope_CSZ
  - VOL_RealizedSkew20_CSR
  - VOL_RealizedSkew20_TSR_252D
  - VOL_ReturnKurtosis_TSZ_20D
  - VOL_ReturnVolatility_TSR_252D
  - VOL_Volatility60_CSR
  - VOL_VolatilityParkinson_CSZ
cat_cols:
  - EVT_IsMissingEPS_RAW
  - SEA_DayOfMonth_RAW
  - SEA_MonthInQuarter_RAW