name: tac_gauss_rank
feature_cols:
 - BET_Beta60_SNZ
 - BET_MarketHV20_CSZ
 - BET_MarketReturn_SNZ
 - BET_MarketTrendIdx_CSZ
 - BET_MarketTrendIdx_SNZ
 - BET_RS25_CSZ
 - BET_RS25_TSZ_20D
 - BET_SectorRel_TSZ_20D
 - BET_SectorRelStrength60_CSZ
 - CON_RevisionRate_CSZ
 - CON_RevisionRate_SNZ
 - EVT_EPSActual_CSZ
 - EVT_LogDaysSincePub_SNZ
 - GOV_MarketSegment_RAW
 - LIQ_AmihudIlliq_CSZ
 - LIQ_AmihudIlliq_TSZ_20D
 - MOM_DistHigh250_TSZ_20D
 - MOM_DistHigh60_CSZ
 - MOM_GapRate_TSZ_20D
 - MOM_High52wDist_SNZ
 - MOM_MADev200_CSZ
 - MOM_MADev75_CSZ
 - MOM_MADev75_SNZ
 - MOM_Momentum12-1_CSZ
 - MOM_Momentum12-1_SNZ
 - MOM_NewHighFlag3_SNZ
 - MOM_RCI9Diff_SNZ
 - MOM_RetIntraday_TSZ_20D
 - MOM_Return12m_CSZ
 - MOM_Return1dLag2_SNZ
 - MOM_Return20d_TSZ_20D
 - MOM_Return6m_CSZ
 - MOM_Return6m_SNZ
 - QLT_EquityRatio_CSZ
 - QLT_OperatingProfitGrowthYOY_SNZ
 - QLT_OPMargin_SNZ
 - QLT_ROA_CSZ
 - SEA_IsQuarterEnd_RAW
 - SPD_DistVWAPSlope_CSZ
 - SPD_FlowAccel_CSZ
 - SPD_FlowAccel_TSZ_20D
 - SPD_MarginRatio_CSZ
 - SPD_MarketForeignBuy_TSZ_20D
 - SPD_MarketIndividualBuy_CSZ
 - VAL_EarningsYield_SNZ
 - VOL_ATRRatio_SNZ
 - VOL_DownsideRun_SNZ
 - VOL_HistVol20_SNZ
 - VOL_HVSlope_SNZ
 - VOL_ReturnVolatility_SNZ
 - VOL_UlcerIndex14_TSZ_20D
 - VOL_Volatility60_SNZ
 - VOL_VolatilityParkinson_SNZ
 - VOL_VolRatioHV_TSZ_20D
 - VOL_VolumeMA25_CSZ
cat_cols:
 - GOV_MarketSegment_RAW
 - SEA_IsQuarterEnd_RAW