feature_cols:
  - MOM_MADev200_RAW
  - MOM_DistHigh250_RAW
  - MOM_DistHigh60_CSZ
  - MOM_Return12m_CSR
  - MOM_DistSMA25-75_RAW
  - MOM_RCI26_CSR
  - MOM_Momentum12-1_TSR_252D
  - MOM_RCI52_SNZ
  - MOM_DistHigh250_SNZ
  - MOM_LinRegSlope10_CSZ
  - MOM_Return12m_TSZ_20D
  - MOM_DistSMA25-75_TSZ_20D
  - MOM_Return12m_TSR_252D
  - VOL_Volatility60_CSZ
  - VOL_LargeMoveCount_CSZ
  - VOL_VolumeMA25_SNZ
  - VOL_VolatilityParkinson_CSR
  - VOL_RealizedSkew20_SNZ
  - VOL_RealizedSkew20_TSR_252D
  - VOL_Volatility60_TSR_252D
  - VOL_VolatilityParkinson_SNZ
  - VOL_HV30_TSR_252D
  - VOL_VolumeMA25_TSR_252D
  - QLT_SalesGrowthYOY_SNZ
  - QLT_SalesGrowthYOY_TSR_252D
  - QLT_OperatingProfitGrowthYOY_TSR_252D
  - QLT_ROE_SNZ
  - QLT_OPMargin_RAW
  - QLT_OperatingProfitGrowthYOY_RAW
  - BET_RS25_RAW
  - BET_SectorRelStrength60_RAW
  - BET_Beta60_CSR
  - BET_MarketHV20_SNZ
  - BET_SectorRelStrength60_TSZ_20D
  - SPD_VWAPDev_RAW
  - SPD_MarginRatio_CSZ
  - SPD_VWAPDev_CSZ
  - SPD_MarginBuyImpact_CSR
  - VAL_LogPBR_CSZ
  - VAL_EarningsYield_CSR
  - VAL_LogPBR_SNZ
  - CON_ProgressRate_TSZ_20D
  - CON_ProgressRate_CSZ
  - CON_ProgressRate_TSR_252D
  - CON_ProgressRate_SNZ
  - LIQ_VolSpikeCount20_TSR_252D
  - EVT_EPSActual_SNZ
  - EVT_IsMissingEPS_RAW
  - EVT_LogDaysSincePub_SNZ
  - SEA_IsQuarterEnd_RAW
  - SIZ_LogMarketCap_CSR
  - GOV_MarketSegment_RAW
  - GOV_Sector33Code_RAW
cat_cols:
  - GOV_MarketSegment_RAW
  - GOV_Sector33Code_RAW
  - SEA_IsQuarterEnd_RAW
  - EVT_IsMissingEPS_RAW