feature_cols:
  - BET_MarketHV20_CSR
  - BET_MarketHV20_CSZ
  - BET_MarketReturn_CSZ
  - BET_MarketTrendIdx_CSR
  - BET_MarketVolChange_CSZ
  - BET_SectorMomentum5d_CSZ
  - BET_SectorRelStrength60_CSZ
  - BET_SectorReturn_TSR_252D
  - CON_ProgressRate_TSR_252D
  - CON_RevisionRate_CSR
  - CON_RevisionRate_CSZ
  - EVT_IsMissingEPS_CSR
  - EVT_LogDaysSincePub_CSZ
  - GOV_MarketSegment_RAW
  - LIQ_AmihudIlliq_CSZ
  - LIQ_VolSpikeCount20_CSR
  - LIQ_VolSpikeCount20_TSR_252D
  - LIQ_VolumeLog_CSZ
  - MOM_ADX14_CSZ
  - MOM_DistSMA25-75_CSR
  - MOM_LogReturn_CSZ
  - MOM_NewHighFlag3_CSR
  - MOM_RSI9_CSZ
  - MOM_Return5d_CSZ
  - QLT_OPMargin_CSZ
  - QLT_OperatingProfitGrowthYOY_TSR_252D
  - SEA_DayOfMonth_RAW
  - SEA_MonthInQuarter_RAW
  - SPD_FlowAccel_CSZ
  - SPD_MarketForeignBuy_TSR_252D
  - SPD_OverseaFlowTrend_CSR
  - SPD_OverseaFlowTrend_TSR_252D
  - VAL_EarningsYield_CSZ
  - VOL_ATRSqueeze_TSR_252D
  - VOL_HV30_TSR_252D
cat_cols:
  - GOV_MarketSegment_RAW
  - SEA_DayOfMonth_RAW
  - SEA_MonthInQuarter_RAW