name: tac_PureTS
feature_cols:
- BET_Beta60_RAW
- BET_MarketHV20_RAW
- BET_MarketTrendIdx_TSZ_20D
- BET_MarketVolChange_TSZ_20D
- BET_RS25_TSZ_20D
- BET_SectorMomentum5d_TSZ_20D
- BET_SectorRelStrength60_RAW
- BET_SectorRel_RAW
- CON_ProgressRate_RAW
- EVT_LogDaysSincePub_RAW
- GOV_MarketSegment_RAW
- GOV_Sector33Code_RAW
- LIQ_AmihudIlliq_TSZ_20D
- MOM_DistHigh250_TSZ_20D
- MOM_DistKijun_RAW
- MOM_DistSMA25-75_RAW
- MOM_DistSMA5-25_RAW
- MOM_DistSMA5_TSZ_20D
- MOM_GapRate_TSZ_20D
- MOM_IchimokuDist_RAW
- MOM_LinRegSlope10_RAW
- MOM_MACDHistDiff_TSZ_20D
- MOM_MACDHistNorm_TSZ_20D
- MOM_MADev200_RAW
- MOM_MADev25_RAW
- MOM_MADev75_RAW
- MOM_MaxGain5_RAW
- MOM_Momentum12-1_RAW
- MOM_RCI26_RAW
- MOM_RCI52_RAW
- MOM_RetIntraday_TSZ_20D
- MOM_Return12m_TSZ_20D
- MOM_Return20d_TSZ_20D
- MOM_Return3d_TSZ_20D
- MOM_Return5d_TSZ_20D
- MOM_Return6m_TSZ_20D
- QLT_OperatingProfitGrowthYOY_TSZ_20D
- QLT_SalesGrowthYOY_RAW
- SEA_CosDayOfWeek_RAW
- SEA_DayOfMonth_RAW
- SEA_DayOfWeek_RAW
- SEA_IsGotobi_RAW
- SEA_IsMonthEnd_RAW
- SEA_IsQuarterEnd_RAW
- SEA_MonthInQuarter_RAW
- SEA_Quarter_RAW
- SEA_SinDayOfWeek_RAW
- SEA_TimeIdx_RAW
- SPD_DistVWAP5_TSZ_20D
- SPD_FlowAccel_TSZ_20D
- SPD_MarketForeignBuy_RAW
- SPD_MarketIndividualBuy_RAW
- SPD_OverseaFlowTrend_RAW
- SPD_VWAPDev_RAW
- VAL_LogPBR_TSZ_20D
- VOL_ATRRatio_RAW
- VOL_ATRSqueezeBB_RAW
- VOL_ATRSqueeze_TSZ_20D
- VOL_DownsideDev60_RAW
- VOL_DownsideRun_RAW
- VOL_GapAbs_RAW
- VOL_HV30_RAW
- VOL_HistVol20_RAW
- VOL_LargeMoveCount_RAW
- VOL_MAE10_RAW
- VOL_MAE5_RAW
- VOL_RangeRatioLong_TSZ_20D
- VOL_ReturnVolatility_TSZ_20D
- VOL_UlcerIndex14_RAW
- VOL_VolRatioHV_TSZ_20D
- VOL_Volatility60_RAW
- VOL_VolatilityParkinson_RAW
cat_cols:
- GOV_MarketSegment_RAW
- GOV_Sector33Code_RAW
- SEA_DayOfMonth_RAW
- SEA_DayOfWeek_RAW
- SEA_IsGotobi_RAW
- SEA_IsMonthEnd_RAW
- SEA_IsQuarterEnd_RAW
- SEA_MonthInQuarter_RAW
- SEA_Quarter_RAW
