name: tac_vol_scaled_residual
feature_cols:
 - BET_Beta60_TSZ_20D
 - BET_MarketHV20_RAW
 - BET_MarketTrendIdx_TSZ_20D
 - BET_SectorMomentum5d_TSZ_20D
 - BET_SectorRel_TSZ_20D
 - BET_SectorRelStrength60_RAW
 - GOV_MarketSegment_RAW
 - MOM_DistKijun_RAW
 - MOM_DistSMA25-75_RAW
 - MOM_DistSMA25-75_TSZ_20D
 - MOM_DistSMA5_TSZ_20D
 - MOM_MADev25_RAW
 - MOM_MADev75_RAW
 - MOM_MaxGain5_TSZ_20D
 - MOM_Return20d_TSZ_20D
 - MOM_Return5d_TSZ_20D
 - QLT_SalesGrowthYOY_RAW
 - QLT_SalesGrowthYOY_TSZ_20D
 - SEA_DayOfWeek_RAW
 - SEA_IsQuarterEnd_RAW
 - SEA_MonthInQuarter_RAW
 - SEA_Quarter_RAW
 - SPD_DistVWAP5_TSZ_20D
 - SPD_FlowAccel_TSZ_20D
 - SPD_MarketIndividualBuy_RAW
 - SPD_MarketIndividualBuy_TSZ_20D
 - SPD_OverseaFlowTrend_RAW
 - SPD_VWAPDev_RAW
 - VOL_ATRRatio_RAW
 - VOL_ATRRatio_TSZ_20D
 - VOL_DownsideDev60_TSZ_20D
 - VOL_GapAbs_TSZ_20D
 - VOL_HistVol20_TSZ_20D
 - VOL_HV30_RAW
 - VOL_MAE5_RAW
 - VOL_RangeRatioLong_TSZ_20D
 - VOL_UlcerIndex14_TSZ_20D
 - VOL_Volatility60_RAW
 - VOL_VolatilityParkinson_TSZ_20D
 - VOL_VolRatioHV_TSZ_20D
cat_cols:
 - GOV_MarketSegment_RAW
 - SEA_IsQuarterEnd_RAW