name: str_gauss_rank
feature_cols:
 - BET_Beta60_CSZ
 - BET_Beta60_SNZ
 - BET_MarketHV20_CSZ
 - BET_MarketHV20_SNZ
 - BET_MarketReturn_CSZ
 - BET_MarketTrendIdx_CSZ
 - BET_MarketTrendIdx_TSR_252D
 - BET_MarketVolChange_CSZ
 - BET_MarketVolChange_TSR_252D
 - BET_SectorRel_SNZ
 - BET_SectorRel_TSR_252D
 - BET_SectorRelStrength60_CSZ
 - BET_SectorRelStrength60_SNZ
 - BET_SectorRelStrength60_TSR_252D
 - BET_SectorReturn_CSZ
 - BET_SectorReturn_SNZ
 - BET_SectorReturn_TSR_252D
 - CON_ProgressRate_TSR_252D
 - CON_RevisionRate_CSZ
 - EVT_EPSActual_CSZ
 - EVT_EPSActual_SNZ
 - EVT_IsMissingEPS_CSZ
 - GOV_MarketSegment_CSZ
 - LIQ_LogTradingCap_CSZ
 - LIQ_TurnoverRatio_CSZ
 - MOM_DistHigh60_CSZ
 - MOM_DistSMA25-75_CSZ
 - MOM_High52wDist_SNZ
 - MOM_LinRegSlope10_CSR
 - MOM_MADev200_CSZ
 - MOM_MADev75_CSZ
 - MOM_NewHighFlag3_TSR_252D
 - MOM_PricePos120_SNZ
 - MOM_Return12m_SNZ
 - MOM_Return6m_CSZ
 - QLT_Accruals_CSZ
 - QLT_Accruals_SNZ
 - QLT_Accruals_TSR_252D
 - QLT_EquityRatio_CSZ
 - QLT_OperatingProfitGrowthYOY_SNZ
 - QLT_OperatingProfitGrowthYOY_TSR_252D
 - QLT_OPMargin_CSZ
 - QLT_OPMargin_SNZ
 - QLT_OPMargin_TSR_252D
 - QLT_ROA_SNZ
 - QLT_ROE_SNZ
 - SEA_CosDayOfWeek_RAW
 - SEA_SinDayOfWeek_RAW
 - SIZ_LogMarketCap_CSZ
 - SPD_MarginBuyImpact_CSZ
 - SPD_MarginRatio_CSZ
 - SPD_MarketForeignBuy_CSZ
 - SPD_MarketForeignBuy_TSR_252D
 - SPD_MarketIndividualBuy_CSZ
 - SPD_MarketIndividualBuy_TSR_252D
 - SPD_OverseaFlowTrend_TSR_252D
 - SPD_VWAPDev_CSR
 - SPD_VWAPDev_CSZ
 - VAL_EarningsYield_CSZ
 - VAL_LogPBR_CSZ
 - VAL_LogPBR_SNZ
 - VAL_LogPBR_TSR_252D
 - VOL_ATRRatio_CSZ
 - VOL_HistVol20_CSZ
 - VOL_HV30_CSZ
 - VOL_LargeMoveCount_CSZ
 - VOL_Volatility60_CSZ
 - VOL_VolatilityParkinson_CSZ
 - VOL_VolatilityParkinson_TSR_252D
cat_cols:
 - GOV_MarketSegment_CSZ