feature_cols:
- BET_Beta60_RAW
- BET_Beta60_SNZ
- BET_Beta60_TSZ_20D
- BET_MarketHV20_CSZ
- BET_MarketHV20_TSR_252D
- BET_MarketHV20_TSZ_20D
- BET_MarketReturn_SNZ
- BET_MarketReturn_TSR_252D
- BET_MarketTrendIdx_TSR_252D
- BET_MarketTrendIdx_TSZ_20D
- BET_RS25_CSZ
- BET_SectorMomentum5d_CSZ
- BET_SectorRelStrength60_CSZ
- BET_SectorRelStrength60_TSR_252D
- BET_SectorRel_RAW
- BET_SectorReturn_CSR
- CON_ProgressRate_CSR
- CON_ProgressRate_SNZ
- CON_ProgressRate_TSZ_20D
- CON_RevisionRate_CSR
- CON_RevisionRate_CSZ
- CON_RevisionRate_RAW
- CON_RevisionRate_TSR_252D
- EVT_EPSActual_SNZ
- EVT_IsMissingEPS_RAW
- EVT_LogDaysSincePub_RAW
- GOV_MarketSegment_RAW
- GOV_Sector33Code_RAW
- LIQ_AbnormalVolume_RAW
- LIQ_AmihudIlliq_CSR
- LIQ_AmihudIlliq_CSZ
- LIQ_MFI14_CSZ
- LIQ_TurnoverRatio_RAW
- LIQ_VolSpikeCount20_CSR
- LIQ_VolSpikeCount20_TSR_252D
- LIQ_VolSpikeCount20_TSZ_20D
- LIQ_VolUpDownRatio_TSR_252D
- LIQ_VolumeChange_TSZ_20D
- LIQ_VolumeLog_RAW
- LIQ_VolumeSlope5_RAW
- MOM_ADX14_RAW
- MOM_ADX14_TSZ_20D
- MOM_BodyRatio_RAW
- MOM_BullishRatio20_SNZ
- MOM_BullishRatio20_TSR_252D
- MOM_DistHigh250_RAW
- MOM_DistHigh250_SNZ
- MOM_DistHigh60_SNZ
- MOM_DistSMA25-75_CSZ
- MOM_DistSMA25-75_TSZ_20D
- MOM_EfficiencyRatio10_SNZ
- MOM_GapRate_TSZ_20D
- MOM_MACDHistNorm_SNZ
- MOM_MACDHistNorm_TSR_252D
- MOM_MADev200_TSR_252D
- MOM_MADev25_SNZ
- MOM_MADev75_SNZ
- MOM_Momentum12-1_TSR_252D
- MOM_Momentum12-1_TSZ_20D
- MOM_NewHighFlag3_CSR
- MOM_NewHighFlag3_TSR_252D
- MOM_RCI26Diff_TSZ_20D
- MOM_RCI52_SNZ
- MOM_RCI52_TSR_252D
- MOM_RCI52_TSZ_20D
- MOM_RSI9_RAW
- MOM_Return12m_CSZ
- MOM_Return1dLag2_CSR
- MOM_WinRate10d_TSR_252D
- QLT_Accruals_RAW
- QLT_Accruals_TSR_252D
- QLT_Accruals_TSZ_20D
- QLT_EPSGrowthYOY_RAW
- QLT_EPSGrowthYOY_SNZ
- QLT_EPSGrowthYOY_TSZ_20D
- QLT_EquityRatio_RAW
- QLT_EquityRatio_SNZ
- QLT_EquityRatio_TSZ_20D
- QLT_OPMargin_CSZ
- QLT_OPMargin_TSR_252D
- QLT_OperatingProfitGrowthYOY_CSZ
- QLT_OperatingProfitGrowthYOY_SNZ
- QLT_OperatingProfitGrowthYOY_TSR_252D
- QLT_OperatingProfitGrowthYOY_TSZ_20D
- QLT_ROA_SNZ
- QLT_ROE_RAW
- QLT_ROE_TSR_252D
- QLT_SalesGrowthYOY_SNZ
- QLT_SalesGrowthYOY_TSR_252D
- QLT_SalesGrowthYOY_TSZ_20D
- SEA_DayOfMonth_RAW
- SEA_DayOfWeek_RAW
- SEA_MonthInQuarter_RAW
- SEA_Quarter_RAW
- SIZ_LogMarketCap_CSZ
- SPD_DistVWAP5_TSR_252D
- SPD_FlowAccel_TSZ_20D
- SPD_MarginBuyImpact_CSZ
- SPD_MarginBuyImpact_RAW
- SPD_MarginBuyImpact_TSR_252D
- SPD_MarginBuyImpact_TSZ_20D
- SPD_MarginRatioDelta4w_RAW
- SPD_MarginRatio_CSZ
- SPD_MarketForeignBuy_CSZ
- SPD_MarketForeignBuy_TSR_252D
- SPD_MarketIndividualBuy_CSZ
- SPD_MarketIndividualBuy_RAW
- SPD_MarketIndividualBuy_TSZ_20D
- SPD_OverseaFlowTrend_TSR_252D
- SPD_OverseaFlowTrend_TSZ_20D
- SPD_VWAPDev_CSZ
- SPD_VWAPDev_RAW
- SPD_VWAPDev_TSR_252D
- VAL_EarningsYield_RAW
- VAL_EarningsYield_SNZ
- VAL_EarningsYield_TSR_252D
- VAL_LogPBR_CSR
- VAL_LogPBR_SNZ
- VAL_LogPBR_TSR_252D
- VOL_ATRRatio_TSZ_20D
- VOL_ATRSqueezeBB_TSR_252D
- VOL_ATRSqueeze_TSZ_20D
- VOL_BBWidth_CSZ
- VOL_DownsideDev60_TSR_252D
- VOL_DownsideDev60_TSZ_20D
- VOL_DownsideRun_RAW
- VOL_GapAbs_CSR
- VOL_HV30_TSZ_20D
- VOL_HVSlope_CSZ
- VOL_HVSlope_TSZ_20D
- VOL_HistVol20_CSZ
- VOL_HistVol20_SNZ
- VOL_HistVol20_TSR_252D
- VOL_HistVol20_TSZ_20D
- VOL_RealizedSkew20_TSR_252D
- VOL_ReturnVolatility_RAW
- VOL_ReturnVolatility_TSR_252D
- VOL_UlcerIndex14_CSR
- VOL_UlcerIndex14_TSZ_20D
- VOL_VolRatioHV_TSZ_20D
- VOL_Volatility60_RAW
- VOL_Volatility60_SNZ
- VOL_Volatility60_TSZ_20D
- VOL_VolumeMA25_SNZ
- VOL_VolumeMA25_TSR_252D
- VOL_VolumeMA25_TSZ_20D
cat_cols:
- EVT_IsMissingEPS_RAW
- GOV_MarketSegment_RAW
- GOV_Sector33Code_RAW
- SEA_DayOfMonth_RAW
- SEA_DayOfWeek_RAW
- SEA_MonthInQuarter_RAW
- SEA_Quarter_RAW