feature_cols:
- SPD_VWAPDev_CSZ
- VOL_VolatilityParkinson_CSR
- VAL_LogPBR_CSZ
- VOL_DownsideDev60_CSR
- SPD_MarginRatio_RAW
- SPD_VWAPDev_CSR
- VAL_LogPBR_SNZ
- VOL_HV30_CSZ
- VAL_EarningsYield_CSR
- MOM_LinRegSlope10_CSZ
- BET_SectorRelStrength60_TSR_252D
- VOL_ATRRatio_TSR_252D
- LIQ_AmihudIlliq_CSZ
- BET_SectorRelStrength60_CSZ
- LIQ_TurnoverRatio_RAW
- EVT_IsMissingEPS_RAW
- LIQ_LogTradingCap_CSR
cat_cols:
- EVT_IsMissingEPS_RAW