target_name: str_sharpe_adj
feature_count: 110
feature_cols:
  - BET_Beta60_SNZ
  - BET_RS25_SNZ
  - BET_SectorRelStrength60_SNZ
  - BET_SectorRel_SNZ
  - BET_SectorReturn_SNZ
  - EVT_EPSActual_SNZ
  - EVT_IsMissingEPS_RAW
  - EVT_LogDaysSincePub_RAW
  - MOM_ADX14_SNZ
  - MOM_ADX14_TSZ_20D
  - MOM_BBPercentB_SNZ
  - MOM_BBPercentB_TSZ_20D
  - MOM_BodyRatio_SNZ
  - MOM_BodyRatio_TSZ_20D
  - MOM_BullishRatio20_SNZ
  - MOM_BullishRatio20_TSZ_20D
  - MOM_ClosePosition_SNZ
  - MOM_ClosePosition_TSZ_20D
  - MOM_DistHigh250_SNZ
  - MOM_DistHigh250_TSZ_20D
  - MOM_DistHigh60_SNZ
  - MOM_DistHigh60_TSZ_20D
  - MOM_DistKijun_SNZ
  - MOM_DistKijun_TSZ_20D
  - MOM_DistSMA25-75_SNZ
  - MOM_DistSMA25-75_TSZ_20D
  - MOM_DistSMA25_SNZ
  - MOM_DistSMA25_TSZ_20D
  - MOM_DistSMA75_SNZ
  - MOM_DistSMA75_TSZ_20D
  - MOM_EfficiencyRatio10_SNZ
  - MOM_EfficiencyRatio10_TSZ_20D
  - MOM_High52wDist_SNZ
  - MOM_High52wDist_TSZ_20D
  - MOM_IchimokuDist_SNZ
  - MOM_IchimokuDist_TSZ_20D
  - MOM_IntradayStrength_SNZ
  - MOM_IntradayStrength_TSZ_20D
  - MOM_LinRegSlope10_SNZ
  - MOM_LinRegSlope10_TSZ_20D
  - MOM_LogReturn_SNZ
  - MOM_LogReturn_TSZ_20D
  - MOM_LowerShadowMA5_SNZ
  - MOM_LowerShadowMA5_TSZ_20D
  - MOM_LowerShadowRatio_SNZ
  - MOM_LowerShadowRatio_TSZ_20D
  - MOM_MACDHistDiff_SNZ
  - MOM_MACDHistDiff_TSZ_20D
  - MOM_MACDHistNorm_SNZ
  - MOM_MACDHistNorm_TSZ_20D
  - MOM_MADev200_SNZ
  - MOM_MADev200_TSZ_20D
  - MOM_MADev25_SNZ
  - MOM_MADev25_TSZ_20D
  - MOM_MADev75_SNZ
  - MOM_MADev75_TSZ_20D
  - MOM_Momentum12-1_SNZ
  - MOM_Momentum12-1_TSZ_20D
  - MOM_PricePos120_SNZ
  - MOM_PricePos120_TSZ_20D
  - MOM_RCI26Diff_SNZ
  - MOM_RCI26Diff_TSZ_20D
  - MOM_RCI26_SNZ
  - MOM_RCI26_TSZ_20D
  - MOM_RCI52_SNZ
  - MOM_RCI52_TSZ_20D
  - MOM_RCI9Diff_SNZ
  - MOM_RCI9Diff_TSZ_20D
  - MOM_RCI9_SNZ
  - MOM_RCI9_TSZ_20D
  - MOM_RSI9-14Diff_SNZ
  - MOM_RSI9-14Diff_TSZ_20D
  - MOM_RSI9_SNZ
  - MOM_RSI9_TSZ_20D
  - MOM_Return10d_SNZ
  - MOM_Return10d_TSZ_20D
  - MOM_Return12m_SNZ
  - MOM_Return12m_TSZ_20D
  - MOM_Return20d_SNZ
  - MOM_Return20d_TSZ_20D
  - MOM_Return6m_SNZ
  - MOM_Return6m_TSZ_20D
  - MOM_Streak_SNZ
  - MOM_Streak_TSZ_20D
  - MOM_UpperShadowRatio_SNZ
  - MOM_UpperShadowRatio_TSZ_20D
  - MOM_WinRate10d_SNZ
  - MOM_WinRate10d_TSZ_20D
  - VAL_EarningsYield_SNZ
  - VAL_LogPBR_SNZ
  - VOL_ATRChgRate_TSZ_20D
  - VOL_ATRRatio_TSZ_20D
  - VOL_ATRSqueezeBB_TSZ_20D
  - VOL_ATRSqueeze_TSZ_20D
  - VOL_BBWidth_TSZ_20D
  - VOL_DownsideDev60_TSZ_20D
  - VOL_DownsideRun_TSZ_20D
  - VOL_GapAbs_TSZ_20D
  - VOL_HVSlope_TSZ_20D
  - VOL_HistVol20_TSZ_20D
  - VOL_LargeMoveCount_TSZ_20D
  - VOL_MAE10_TSZ_20D
  - VOL_RangeRatioLong_TSZ_20D
  - VOL_RealizedSkew20_TSZ_20D
  - VOL_ReturnKurtosis_TSZ_20D
  - VOL_ReturnSkewnessDiff_TSZ_20D
  - VOL_UlcerIndex14_TSZ_20D
  - VOL_VolRatioHV_TSZ_20D
  - VOL_Volatility60_TSZ_20D
  - VOL_VolumeMA25_TSZ_20D
cat_cols:
  - EVT_IsMissingEPS_RAW