name: str_sharpe_adj
feature_cols:
 - BET_Beta60_CSR
 - BET_Beta60_CSZ
 - BET_Beta60_TSR_252D
 - BET_Beta60_SNZ
 - CON_ProgressRate_CSR
 - CON_ProgressRate_TSR_252D
 - EVT_EPSActual_TSR_252D
 - EVT_IsMissingEPS_CSR
 - EVT_IsMissingEPS_SNZ
 - GOV_MarketSegment_RAW
 - QLT_EquityRatio_CSZ
 - QLT_OperatingProfitGrowthYOY_SNZ
 - QLT_OPMargin_CSR
 - QLT_OPMargin_CSZ
 - QLT_OPMargin_TSR_252D
 - QLT_OPMargin_SNZ
 - QLT_ROA_TSR_252D
 - SEA_Quarter_RAW
 - SPD_MarketIndividualBuy_TSR_252D
 - SPD_MarketIndividualBuy_TSZ_20D
 - SPD_VWAPDev_CSZ
 - SPD_VWAPDev_TSR_252D
 - SPD_VWAPDev_TSZ_20D
 - VAL_EarningsYield_CSR
 - VAL_EarningsYield_TSR_252D
 - VAL_LogPBR_CSR
 - VAL_LogPBR_CSZ
 - VAL_LogPBR_TSZ_20D
 - VAL_LogPBR_TSR_252D
 - VOL_DownsideDev60_CSR
 - VOL_VolumeMA25_CSR
 - VOL_VolumeMA25_TSR_252D
 - VOL_VolumeMA25_TSZ_20D
cat_cols:
 - GOV_MarketSegment_RAW
 - SEA_Quarter_RAW