target_name: tac_vol_scaled_asym_return
feature_count: 75
feature_cols:
  - BET_RS25_CSR
  - BET_RelSectorReturn1d_CSR
  - BET_RelSectorReturn5d_CSR
  - BET_SectorMomentum5d_CSR
  - BET_SectorRel_CSR
  - BET_SectorReturn_CSR
  - EVT_IsMissingEPS_RAW
  - EVT_LogDaysSincePub_RAW
  - LIQ_AbnormalVolume_CSZ
  - LIQ_AmihudIlliq_CSZ
  - LIQ_LogTradingCap_CSZ
  - LIQ_MFI14_CSZ
  - LIQ_TurnoverRatio_CSZ
  - LIQ_VolRatio5d_CSZ
  - LIQ_VolSpikeCount20_CSZ
  - LIQ_VolUpDownRatio_CSZ
  - LIQ_VolumeChange_CSZ
  - LIQ_VolumeSlope5_CSZ
  - MOM_ADX14_CSR
  - MOM_BBPercentB_CSR
  - MOM_BodyRatio_CSR
  - MOM_BullishRatio20_CSR
  - MOM_ClosePosition_CSR
  - MOM_DistKijun_CSR
  - MOM_DistSMA25_CSR
  - MOM_DistSMA5-25_CSR
  - MOM_DistSMA5_CSR
  - MOM_EfficiencyRatio10_CSR
  - MOM_GapRate_CSR
  - MOM_High52wDist_CSR
  - MOM_IchimokuDist_CSR
  - MOM_IntradayStrength_CSR
  - MOM_LinRegSlope10_CSR
  - MOM_LogReturn_CSR
  - MOM_LowerShadowMA5_CSR
  - MOM_LowerShadowRatio_CSR
  - MOM_MACDHistDiff_CSR
  - MOM_MACDHistNorm_CSR
  - MOM_MADev200_CSR
  - MOM_MADev25_CSR
  - MOM_MADev75_CSR
  - MOM_MaxGain5_CSR
  - MOM_Momentum12-1_CSR
  - MOM_NewHighFlag3_CSR
  - MOM_RCI26Diff_CSR
  - MOM_RCI26_CSR
  - MOM_RCI52_CSR
  - MOM_RCI9Diff_CSR
  - MOM_RCI9_CSR
  - MOM_RSI9-14Diff_CSR
  - MOM_RSI9_CSR
  - MOM_RetIntraday_CSR
  - MOM_Return20d_CSR
  - MOM_Return5d_CSR
  - MOM_Streak_CSR
  - MOM_UpperShadowRatio_CSR
  - MOM_WinRate10d_CSR
  - VOL_ATRChgRate_CSZ
  - VOL_ATRRatio_CSZ
  - VOL_ATRSqueezeBB_CSZ
  - VOL_ATRSqueeze_CSZ
  - VOL_BBWidth_CSZ
  - VOL_DownsideRun_CSZ
  - VOL_GapAbs_CSZ
  - VOL_HVSlope_CSZ
  - VOL_HistVol20_CSZ
  - VOL_LargeMoveCount_CSZ
  - VOL_MAE10_CSZ
  - VOL_MAE5_CSZ
  - VOL_RangeRatioLong_CSZ
  - VOL_RealizedSkew20_CSZ
  - VOL_ReturnKurtosis_CSZ
  - VOL_ReturnSkewnessDiff_CSZ
  - VOL_UlcerIndex14_CSZ
  - VOL_VolRatioHV_CSZ
cat_cols:
  - EVT_IsMissingEPS_RAW