# Step 3 Feature Selection Result
# Model: LightGBM (TAC)
# Target: tac_vol_scaled_asym_return
# Metric: ndcg@10
# Filter: Feature Sharpe > 0.5
# Total Selected Features: 
feature_cols:
 - VAL_EarningsYield_SNZ
 - VOL_RealizedSkew20_CSZ
 - EVT_LogDaysSincePub_RAW
 - SPD_MarketForeignBuy_RAW
 - LIQ_VolSpikeCount20_TSR_252D
 - SPD_VWAPDev_RAW
 - SPD_MarginBuyImpact_RAW
 - VOL_HV30_TSZ_20D
 - VOL_HV30_TSR_252D
 - MOM_Return6m_RAW
 - QLT_OPMargin_TSR_252D
cat_cols: