name: tac_gauss_rank
feature_cols:
 - BET_Beta60_TSZ_20D
 - BET_MarketHV20_TSZ_20D
 - BET_MarketReturn_CSR
 - BET_MarketReturn_CSZ
 - BET_MarketTrendIdx_TSZ_20D
 - BET_RS25_TSZ_20D
 - CON_RevisionRate_CSR
 - MOM_DistHigh250_TSZ_20D
 - MOM_Momentum12-1_TSZ_20D
 - MOM_NewHighFlag3_CSZ
 - MOM_Return12m_TSZ_20D
 - QLT_ROE_CSZ
 - SEA_CosDayOfWeek_RAW
 - SEA_SinDayOfWeek_RAW
 - SPD_MarketForeignBuy_CSZ
 - SPD_MarketIndividualBuy_CSZ
 - SPD_OverseaFlowTrend_CSZ
 - VAL_EarningsYield_CSZ
 - VAL_LogPBR_CSZ
 - VAL_LogPBR_TSZ_20D
 - VOL_ATRRatio_CSZ
 - VOL_ATRSqueezeBB_CSZ
 - VOL_DownsideDev60_TSZ_20D
 - VOL_HistVol20_CSZ
 - VOL_HV30_CSZ
 - VOL_HVSlope_CSZ
 - VOL_LargeMoveCount_CSZ
 - VOL_ReturnVolatility_CSZ
 - VOL_Volatility60_CSZ
 - VOL_Volatility60_TSZ_20D
 - VOL_VolumeMA25_CSZ
cat_cols: