target_name: str_mdd
feature_count: 64
feature_cols:
  - BET_Beta60_CSR
  - BET_RS25_CSR
  - BET_SectorRelStrength60_CSR
  - BET_SectorRel_CSR
  - BET_SectorReturn_CSR
  - EVT_EPSActual_SNZ
  - EVT_IsMissingEPS_RAW
  - EVT_LogDaysSincePub_RAW
  - LIQ_AbnormalVolume_RAW
  - LIQ_LogTradingCap_RAW
  - LIQ_MFI14_RAW
  - LIQ_TurnoverRatio_RAW
  - LIQ_VolRatio5d_RAW
  - LIQ_VolSpikeCount20_RAW
  - LIQ_VolUpDownRatio_RAW
  - LIQ_VolumeChange_RAW
  - LIQ_VolumeLog_RAW
  - MOM_ADX14_RAW
  - MOM_BBPercentB_RAW
  - MOM_BodyRatio_RAW
  - MOM_BullishRatio20_RAW
  - MOM_ClosePosition_RAW
  - MOM_DistHigh250_RAW
  - MOM_DistHigh60_RAW
  - MOM_DistKijun_RAW
  - MOM_DistSMA25-75_RAW
  - MOM_DistSMA25_RAW
  - MOM_DistSMA5-25_RAW
  - MOM_DistSMA75_RAW
  - MOM_EfficiencyRatio10_RAW
  - MOM_High52wDist_RAW
  - MOM_IchimokuDist_RAW
  - MOM_IntradayStrength_RAW
  - MOM_LinRegSlope10_RAW
  - MOM_LogReturn_RAW
  - MOM_LowerShadowMA5_RAW
  - MOM_LowerShadowRatio_RAW
  - MOM_MACDHistNorm_RAW
  - MOM_MADev200_RAW
  - MOM_MADev25_RAW
  - MOM_MADev75_RAW
  - MOM_Momentum12-1_RAW
  - MOM_PricePos120_RAW
  - MOM_RCI26Diff_RAW
  - MOM_RCI26_RAW
  - MOM_RCI52_RAW
  - MOM_RCI9Diff_RAW
  - MOM_RCI9_RAW
  - MOM_RSI9-14Diff_RAW
  - MOM_RSI9_RAW
  - MOM_Streak_RAW
  - MOM_UpperShadowRatio_RAW
  - MOM_WinRate10d_RAW
  - VAL_EarningsYield_SNZ
  - VAL_EarningsYield_RAW
  - VAL_LogPBR_SNZ
  - VAL_LogPBR_RAW
  - VOL_ATRRatio_RAW
  - VOL_ATRSqueeze_RAW
  - VOL_DownsideDev60_RAW
  - VOL_RealizedSkew20_RAW
  - VOL_ReturnKurtosis_RAW
  - VOL_UlcerIndex14_RAW
  - VOL_Volatility60_RAW
cat_cols:
  - EVT_IsMissingEPS_RAW