
feature_cols:
 - BET_Beta60_CSR
 - BET_Beta60_CSZ
 - BET_Beta60_SNZ
 - BET_Beta60_TSZ_20D
 - BET_MarketHV20_CSR
 - BET_MarketTrendIdx_CSZ
 - BET_RelSectorReturn5d_CSZ
 - BET_RS25_CSZ
 - BET_RS25_TSR_252D
 - BET_SectorMomentum5d_CSR
 - BET_SectorMomentum5d_CSZ
 - BET_SectorMomentum5d_SNZ
 - BET_SectorMomentum5d_TSZ_20D
 - BET_SectorRelStrength60_CSR
 - BET_SectorRelStrength60_CSZ
 - BET_SectorRelStrength60_SNZ
 - BET_SectorRelStrength60_TSR_252D
 - BET_SectorRelStrength60_TSZ_20D
 - CON_ProgressRate_CSR
 - CON_ProgressRate_SNZ
 - CON_ProgressRate_TSR_252D
 - CON_ProgressRate_TSZ_20D
 - CON_RevisionRate_CSR
 - CON_RevisionRate_CSZ
 - CON_RevisionRate_SNZ
 - CON_RevisionRate_TSZ_20D
 - EVT_EPSActual_SNZ
 - EVT_IsMissingEPS_RAW
 - EVT_LogDaysSincePub_CSR
 - EVT_LogDaysSincePub_CSZ
 - EVT_LogDaysSincePub_SNZ
 - GOV_MarketSegment_RAW
 - LIQ_AmihudIlliq_CSZ
 - LIQ_TurnoverRatio_CSR
 - LIQ_TurnoverRatio_CSZ
 - LIQ_VolSpikeCount20_TSR_252D
 - LIQ_VolumeLog_CSZ
 - LIQ_VolUpDownRatio_TSZ_20D
 - MOM_ClosePosition_CSZ
 - MOM_DistHigh250_CSR
 - MOM_DistHigh60_CSR
 - MOM_DistHigh60_CSZ
 - MOM_DistHigh60_RAW
 - MOM_DistSMA25-75_TSR_252D
 - MOM_DistSMA25-75_TSZ_20D
 - MOM_DistSMA75_CSR
 - MOM_GapRate_TSR_252D
 - MOM_High52wDist_SNZ
 - MOM_IchimokuDist_SNZ
 - MOM_LinRegSlope10_SNZ
 - MOM_MACDHistNorm_SNZ
 - MOM_MADev200_SNZ
 - MOM_MADev75_SNZ
 - MOM_MaxGain5_CSZ
 - MOM_Momentum12-1_TSR_252D
 - MOM_Momentum12-1_TSZ_20D
 - MOM_NewHighFlag3_TSR_252D
 - MOM_PricePos120_CSZ
 - MOM_PricePos120_SNZ
 - MOM_RCI26_SNZ
 - MOM_RCI26_TSR_252D
 - MOM_RCI52_CSR
 - MOM_RCI52_CSZ
 - MOM_RCI52_RAW
 - MOM_RCI52_SNZ
 - MOM_RCI52_TSR_252D
 - MOM_Return12m_CSR
 - MOM_Return12m_CSZ
 - MOM_Return12m_TSR_252D
 - MOM_Return12m_TSZ_20D
 - MOM_Return20d_CSZ
 - MOM_Return6m_SNZ
 - MOM_Return6m_TSZ_20D
 - QLT_Accruals_TSR_252D
 - QLT_EPSGrowthYOY_CSR
 - QLT_EquityRatio_TSR_252D
 - QLT_OperatingProfitGrowthYOY_CSR
 - QLT_OperatingProfitGrowthYOY_TSR_252D
 - QLT_OperatingProfitGrowthYOY_TSZ_20D
 - QLT_OPMargin_TSR_252D
 - QLT_ROA_CSR
 - QLT_ROA_CSZ
 - QLT_ROA_TSR_252D
 - QLT_ROE_CSR
 - QLT_ROE_CSZ
 - QLT_ROE_SNZ
 - QLT_SalesGrowthYOY_TSR_252D
 - QLT_SalesGrowthYOY_TSZ_20D
 - SEA_DayOfMonth_RAW
 - SEA_IsQuarterEnd_RAW
 - SEA_MonthInQuarter_RAW
 - SIZ_LogMarketCap_CSZ
 - SPD_FlowAccel_CSR
 - SPD_FlowAccel_CSZ
 - SPD_MarginBuyImpact_CSR
 - SPD_MarginBuyImpact_CSZ
 - SPD_MarginBuyImpact_TSR_252D
 - SPD_MarginRatio_CSR
 - SPD_MarginRatio_CSZ
 - SPD_MarginRatioDelta4w_TSR_252D
 - SPD_MarketForeignBuy_TSR_252D
 - SPD_MarketIndividualBuy_TSR_252D
 - SPD_OverseaFlowTrend_CSR
 - SPD_OverseaFlowTrend_CSZ
 - SPD_OverseaFlowTrend_TSR_252D
 - SPD_VWAPDev_CSR
 - SPD_VWAPDev_CSZ
 - VAL_EarningsYield_CSR
 - VAL_EarningsYield_CSZ
 - VAL_EarningsYield_SNZ
 - VAL_LogPBR_CSR
 - VAL_LogPBR_CSZ
 - VAL_LogPBR_TSR_252D
 - VOL_ATRRatio_CSR
 - VOL_ATRRatio_CSZ
 - VOL_ATRRatio_SNZ
 - VOL_ATRSqueezeBB_TSR_252D
 - VOL_DownsideDev60_CSR
 - VOL_DownsideDev60_CSZ
 - VOL_DownsideDev60_TSR_252D
 - VOL_HistVol20_CSR
 - VOL_HistVol20_CSZ
 - VOL_HistVol20_TSR_252D
 - VOL_HV30_CSR
 - VOL_HV30_CSZ
 - VOL_HV30_TSR_252D
 - VOL_HVSlope_CSR
 - VOL_HVSlope_CSZ
 - VOL_RealizedSkew20_CSR
 - VOL_RealizedSkew20_CSZ
 - VOL_RealizedSkew20_TSR_252D
 - VOL_RealizedSkew20_TSZ_20D
 - VOL_ReturnKurtosis_TSZ_20D
 - VOL_ReturnVolatility_TSR_252D
 - VOL_Volatility60_CSR
 - VOL_Volatility60_CSZ
 - VOL_VolatilityParkinson_CSR
 - VOL_VolatilityParkinson_CSZ
 - VOL_VolatilityParkinson_TSZ_20D
 - VOL_VolumeMA25_SNZ
 - VOL_VolumeMA25_TSR_252D
cat_cols:
 - GOV_MarketSegment_RAW
 - EVT_IsMissingEPS_RAW
 - SEA_DayOfMonth_RAW
 - SEA_IsQuarterEnd_RAW
 - SEA_MonthInQuarter_RAW