name: tac_LGBM_rank
feature_cols:
 - BET_MarketHV20_CSZ
 - BET_MarketHV20_TSZ_20D
 - BET_MarketReturn_CSR
 - BET_MarketReturn_SNZ
 - BET_MarketTrendIdx_CSR
 - BET_MarketTrendIdx_CSZ
 - BET_MarketTrendIdx_TSZ_20D
 - BET_MarketVolChange_CSR
 - BET_MarketVolChange_CSZ
 - BET_MarketVolChange_TSZ_20D
 - BET_RS25_CSZ
 - BET_RS25_TSZ_20D
 - BET_SectorMomentum5d_CSZ
 - BET_SectorMomentum5d_SNZ
 - BET_SectorRel_CSR
 - BET_SectorRel_CSZ
 - BET_SectorRelStrength60_CSZ
 - CON_RevisionRate_CSR
 - EVT_IsMissingEPS_SNZ
 - EVT_LogDaysSincePub_SNZ
 - GOV_MarketSegment_CSZ
 - LIQ_AmihudIlliq_TSZ_20D
 - LIQ_LogTradingCap_CSZ
 - LIQ_TurnoverRatio_CSZ
 - MOM_DistHigh250_TSZ_20D
 - MOM_DistSMA25-75_CSZ
 - MOM_DistSMA25-75_TSZ_20D
 - MOM_DistSMA5_TSZ_20D
 - MOM_MACDHistDiff_SNZ
 - MOM_MACDHistNorm_TSZ_20D
 - MOM_MADev200_CSZ
 - MOM_MADev25_CSZ
 - MOM_MADev75_CSZ
 - MOM_MADev75_SNZ
 - MOM_Momentum12-1_CSZ
 - MOM_Momentum12-1_SNZ
 - MOM_NewHighFlag3_SNZ
 - MOM_RCI26_TSZ_20D
 - MOM_RCI52_SNZ
 - MOM_RCI52_TSZ_20D
 - MOM_RCI9Diff_SNZ
 - MOM_RetIntraday_SNZ
 - MOM_Return12m_CSZ
 - MOM_Return12m_SNZ
 - MOM_Return1dLag2_SNZ
 - MOM_Return20d_CSZ
 - MOM_Return5d_CSZ
 - MOM_Return5d_TSZ_20D
 - MOM_Return6m_CSZ
 - MOM_Return6m_TSZ_20D
 - QLT_EquityRatio_CSZ
 - QLT_OperatingProfitGrowthYOY_SNZ
 - QLT_OperatingProfitGrowthYOY_TSZ_20D
 - QLT_OPMargin_SNZ
 - QLT_SalesGrowthYOY_CSZ
 - QLT_SalesGrowthYOY_SNZ
 - SEA_CosDayOfWeek_RAW
 - SEA_SinDayOfWeek_RAW
 - SIZ_LogMarketCap_CSZ
 - SPD_FlowAccel_CSZ
 - SPD_MarginBuyImpact_CSZ
 - SPD_MarginRatio_CSZ
 - SPD_MarketForeignBuy_CSZ
 - SPD_MarketIndividualBuy_CSR
 - SPD_OverseaFlowTrend_CSZ
 - SPD_OverseaFlowTrend_TSZ_20D
 - SPD_VWAPDev_CSR
 - SPD_VWAPDev_CSZ
 - VAL_EarningsYield_CSZ
 - VAL_LogPBR_CSZ
 - VOL_ATRRatio_CSZ
 - VOL_ATRRatio_TSZ_20D
 - VOL_ATRSqueeze_TSZ_20D
 - VOL_DownsideDev60_SNZ
 - VOL_DownsideDev60_TSZ_20D
 - VOL_HistVol20_TSZ_20D
 - VOL_HVSlope_SNZ
 - VOL_MAE5_TSZ_20D
 - VOL_RangeRatioLong_TSZ_20D
 - VOL_ReturnVolatility_CSZ
 - VOL_UlcerIndex14_CSZ
 - VOL_UlcerIndex14_TSZ_20D
 - VOL_Volatility60_CSZ
 - VOL_Volatility60_TSZ_20D
 - VOL_VolatilityParkinson_CSZ
 - VOL_VolatilityParkinson_SNZ
 - VOL_VolRatioHV_TSZ_20D
 - VOL_VolumeMA25_SNZ
cat_cols:
- EVT_IsMissingEPS_RAW
- GOV_market_segment_RAW