feature_cols:
  - BET_SectorRelStrength60_RAW
  - BET_RS25_RAW
  - BET_MarketHV20_TSR_252D
  - BET_MarketHV20_SNZ
  - CON_ProgressRate_RAW
  - EVT_EPSActual_SNZ
  - LIQ_TurnoverRatio_CSR
  - LIQ_VolSpikeCount20_TSR_252D
  - LIQ_VolSpikeCount20_CSR
  - LIQ_AmihudIlliq_CSZ
  - MOM_MADev200_RAW
  - MOM_Return12m_CSR
  - MOM_DistHigh250_RAW
  - MOM_Return20d_CSZ
  - MOM_DistSMA25-75_TSZ_20D
  - MOM_DistHigh60_RAW
  - MOM_RCI52_TSR_252D
  - MOM_RCI52_TSZ_20D
  - MOM_BullishRatio20_CSR
  - MOM_Return12m_TSR_252D
  - QLT_SalesGrowthYOY_TSR_252D
  - QLT_SalesGrowthYOY_SNZ
  - QLT_SalesGrowthYOY_RAW
  - QLT_OperatingProfitGrowthYOY_TSR_252D
  - QLT_OPMargin_SNZ
  - QLT_ROE_SNZ
  - QLT_SalesGrowthYOY_TSZ_20D
  - SEA_IsQuarterEnd_RAW
  - SIZ_LogMarketCap_RAW
  - SPD_VWAPDev_RAW
  - SPD_MarginRatio_CSZ
  - SPD_VWAPDev_CSZ
  - SPD_OverseaFlowTrend_CSR
  - SPD_MarketIndividualBuy_RAW
  - VAL_EarningsYield_CSR
  - VAL_LogPBR_SNZ
  - VAL_EarningsYield_SNZ
  - VOL_VolatilityParkinson_CSR
  - VOL_LargeMoveCount_CSZ
  - VOL_DownsideDev60_CSR
  - VOL_VolumeMA25_SNZ
  - VOL_ATRSqueeze_TSR_252D
  - VOL_VolatilityParkinson_SNZ
  - VOL_VolumeMA25_TSR_252D
  - VOL_HV30_TSR_252D
  - VOL_HVSlope_TSZ_20D
cat_cols:
  - SEA_IsQuarterEnd_RAW