
feature_cols:
- CON_RevisionRate_CSR
- LIQ_AmihudIlliq_CSZ
- SPD_MarketIndividualBuy_CSZ
- MOM_NewHighFlag3_CSZ
- QLT_ROA_TSR_252D
- MOM_BullishRatio20_TSR_252D
- CON_RevisionRate_CSZ
- MOM_ADX14_CSR
- BET_Beta60_TSZ_20D
- VOL_ReturnVolatility_SNZ
- VOL_ReturnKurtosis_SNZ
- SPD_VWAPDev_CSR
- VOL_ATRSqueezeBB_TSZ_20D
- QLT_OPMargin_TSZ_20D
- MOM_MADev200_TSR_252D
- VOL_LargeMoveCount_TSZ_20D
- MOM_Return20d_CSZ
- BET_SectorMomentum5d_CSR
- VOL_VolumeMA25_TSR_252D
- CON_ProgressRate_CSR
- MOM_ADX14_TSZ_20D
- VAL_LogPBR_SNZ
- LIQ_MFI14_CSZ
- VOL_MAE10_CSZ
- BET_SectorRelStrength60_SNZ
- GOV_MarketSegment_RAW
- GOV_Sector33Code_RAW
- SEA_DayOfMonth_RAW
- SEA_IsQuarterEnd_RAW
- SEA_Quarter_RAW
cat_cols:
- GOV_MarketSegment_RAW
- GOV_Sector33Code_RAW
- SEA_DayOfMonth_RAW
- SEA_IsQuarterEnd_RAW
- SEA_Quarter_RAW
