feature_cols:
- BET_Beta60_CSR
- BET_Beta60_TSR_252D
- BET_MarketHV20_CSZ
- BET_MarketHV20_RAW
- BET_MarketHV20_SNZ
- BET_MarketHV20_TSZ_20D
- BET_MarketReturn_CSZ
- BET_MarketTrendIdx_RAW
- BET_MarketTrendIdx_TSZ_20D
- BET_MarketVolChange_TSR_252D
- BET_RS25_TSR_252D
- BET_SectorMomentum5d_CSZ
- BET_SectorMomentum5d_RAW
- BET_SectorMomentum5d_TSZ_20D
- BET_SectorRelStrength60_CSZ
- BET_SectorRelStrength60_RAW
- BET_SectorRelStrength60_SNZ
- BET_SectorRelStrength60_TSR_252D
- BET_SectorRelStrength60_TSZ_20D
- BET_SectorRel_CSR
- BET_SectorRel_SNZ
- BET_SectorReturn_CSZ
- BET_SectorReturn_TSZ_20D
- CON_ProgressRate_CSR
- CON_ProgressRate_RAW
- CON_ProgressRate_SNZ
- CON_ProgressRate_TSR_252D
- CON_RevisionRate_CSR
- CON_RevisionRate_CSZ
- CON_RevisionRate_SNZ
- CON_RevisionRate_TSR_252D
- EVT_EPSActual_SNZ
- EVT_IsMissingEPS_CSZ
- EVT_IsMissingEPS_SNZ
- EVT_LogDaysSincePub_CSZ
- GOV_MarketSegment_RAW
- GOV_Sector33Code_RAW
- LIQ_AmihudIlliq_CSR
- LIQ_AmihudIlliq_CSZ
- LIQ_LogTradingCap_CSR
- LIQ_MFI14_CSZ
- LIQ_TurnoverRatio_RAW
- LIQ_TurnoverRatio_TSR_252D
- LIQ_VolSpikeCount20_CSR
- LIQ_VolSpikeCount20_TSR_252D
- LIQ_VolUpDownRatio_CSZ
- MOM_ADX14_RAW
- MOM_ClosePosition_TSR_252D
- MOM_DistHigh250_RAW
- MOM_DistHigh250_TSR_252D
- MOM_DistHigh60_RAW
- MOM_DistHigh60_TSR_252D
- MOM_DistHigh60_TSZ_20D
- MOM_DistSMA25-75_RAW
- MOM_DistSMA25-75_TSZ_20D
- MOM_DistSMA5-25_SNZ
- MOM_DistSMA75_SNZ
- MOM_GapRate_RAW
- MOM_IchimokuDist_TSR_252D
- MOM_LinRegSlope10_CSZ
- MOM_LinRegSlope10_RAW
- MOM_MaxGain5_RAW
- MOM_Momentum12-1_RAW
- MOM_Momentum12-1_TSR_252D
- MOM_NewHighFlag3_CSR
- MOM_PricePos120_RAW
- MOM_RCI26_CSZ
- MOM_RCI26_TSR_252D
- MOM_RCI52_CSZ
- MOM_RCI52_TSR_252D
- MOM_RCI52_TSZ_20D
- MOM_RCI9_CSZ
- MOM_Return12m_SNZ
- MOM_Return12m_TSR_252D
- MOM_Return6m_RAW
- QLT_Accruals_CSZ
- QLT_Accruals_TSR_252D
- QLT_EPSGrowthYOY_RAW
- QLT_EPSGrowthYOY_TSR_252D
- QLT_EquityRatio_CSR
- QLT_EquityRatio_TSR_252D
- QLT_OPMargin_CSR
- QLT_OPMargin_SNZ
- QLT_OPMargin_TSR_252D
- QLT_OPMargin_TSZ_20D
- QLT_OperatingProfitGrowthYOY_CSR
- QLT_OperatingProfitGrowthYOY_TSR_252D
- QLT_OperatingProfitGrowthYOY_TSZ_20D
- QLT_ROA_CSZ
- QLT_ROE_SNZ
- QLT_ROE_TSR_252D
- QLT_ROE_TSZ_20D
- QLT_SalesGrowthYOY_RAW
- QLT_SalesGrowthYOY_TSR_252D
- QLT_SalesGrowthYOY_TSZ_20D
- SEA_IsQuarterEnd_RAW
- SEA_Quarter_RAW
- SIZ_LogMarketCap_CSZ
- SPD_DistVWAP5_TSR_252D
- SPD_DistVWAPSlope_TSR_252D
- SPD_FlowAccel_CSR
- SPD_FlowAccel_TSR_252D
- SPD_FlowAccel_TSZ_20D
- SPD_MarginBuyImpact_CSR
- SPD_MarginBuyImpact_CSZ
- SPD_MarginBuyImpact_TSR_252D
- SPD_MarginRatio_RAW
- SPD_MarginRatio_TSR_252D
- SPD_MarketForeignBuy_TSR_252D
- SPD_MarketIndividualBuy_RAW
- SPD_OverseaFlowTrend_TSR_252D
- SPD_VWAPDev_CSR
- SPD_VWAPDev_CSZ
- VAL_EarningsYield_CSR
- VAL_EarningsYield_SNZ
- VAL_EarningsYield_TSR_252D
- VAL_LogPBR_CSZ
- VAL_LogPBR_SNZ
- VAL_LogPBR_TSR_252D
- VOL_ATRRatio_RAW
- VOL_ATRRatio_TSR_252D
- VOL_ATRSqueeze_RAW
- VOL_BBWidth_CSZ
- VOL_BBWidth_TSR_252D
- VOL_DownsideDev60_CSR
- VOL_DownsideDev60_RAW
- VOL_DownsideDev60_TSR_252D
- VOL_DownsideRun_TSR_252D
- VOL_HV30_CSZ
- VOL_HV30_TSR_252D
- VOL_HistVol20_TSR_252D
- VOL_LargeMoveCount_RAW
- VOL_LargeMoveCount_TSR_252D
- VOL_LargeMoveCount_TSZ_20D
- VOL_MAE10_CSZ
- VOL_RealizedSkew20_CSZ
- VOL_ReturnVolatility_RAW
- VOL_ReturnVolatility_TSR_252D
- VOL_UlcerIndex14_RAW
- VOL_Volatility60_TSR_252D
- VOL_VolatilityParkinson_CSR
- VOL_VolatilityParkinson_SNZ
- VOL_VolatilityParkinson_TSZ_20D
- VOL_VolumeMA25_CSR
- VOL_VolumeMA25_TSR_252D
cat_cols:
- GOV_MarketSegment_RAW
- GOV_Sector33Code_RAW
- SEA_IsQuarterEnd_RAW
- SEA_Quarter_RAW