name: str_rank
feature_cols:
 - BET_MarketHV20_CSZ
 - BET_MarketHV20_SNZ
 - BET_MarketReturn_TSR_252D
 - BET_MarketTrendIdx_CSZ
 - BET_MarketTrendIdx_TSR_252D
 - BET_MarketVolChange_CSZ
 - BET_MarketVolChange_TSR_252D
 - BET_SectorMomentum5d_SNZ
 - BET_SectorRel_SNZ
 - BET_SectorRel_TSR_252D
 - BET_SectorRelStrength60_CSZ
 - BET_SectorRelStrength60_TSR_252D
 - BET_SectorReturn_CSZ
 - BET_SectorReturn_SNZ
 - CON_ProgressRate_SNZ
 - CON_ProgressRate_TSR_252D
 - CON_RevisionRate_CSR
 - CON_RevisionRate_CSZ
 - EVT_EPSActual_CSZ
 - EVT_IsMissingEPS_CSZ
 - GOV_MarketSegment_CSZ
 - LIQ_LogTradingCap_CSZ
 - LIQ_TurnoverRatio_CSZ
 - MOM_High52wDist_SNZ
 - MOM_LinRegSlope10_CSR
 - MOM_MADev200_SNZ
 - MOM_MADev75_CSZ
 - MOM_Momentum12-1_SNZ
 - MOM_NewHighFlag3_SNZ
 - MOM_NewHighFlag3_TSR_252D
 - MOM_PricePos120_SNZ
 - MOM_Return6m_CSZ
 - QLT_Accruals_CSZ
 - QLT_EquityRatio_CSZ
 - QLT_OperatingProfitGrowthYOY_SNZ
 - QLT_OperatingProfitGrowthYOY_TSR_252D
 - QLT_OPMargin_CSZ
 - QLT_OPMargin_SNZ
 - SEA_CosDayOfWeek_RAW
 - SEA_SinDayOfWeek_RAW
 - SPD_MarginBuyImpact_CSZ
 - SPD_MarginRatio_CSZ
 - SPD_MarketForeignBuy_TSR_252D
 - SPD_MarketIndividualBuy_CSZ
 - SPD_OverseaFlowTrend_TSR_252D
 - SPD_VWAPDev_CSR
 - SPD_VWAPDev_CSZ
 - VAL_EarningsYield_CSZ
 - VAL_EarningsYield_SNZ
 - VAL_LogPBR_CSZ
 - VAL_LogPBR_SNZ
 - VAL_LogPBR_TSR_252D
 - VOL_ATRRatio_CSZ
 - VOL_ATRRatio_TSR_252D
 - VOL_DownsideDev60_CSZ
 - VOL_HistVol20_TSR_252D
 - VOL_HV30_CSZ
 - VOL_LargeMoveCount_CSZ
 - VOL_Volatility60_CSZ
 - VOL_Volatility60_TSR_252D
 - VOL_VolatilityParkinson_CSZ
 - VOL_VolatilityParkinson_SNZ
 - VOL_VolatilityParkinson_TSR_252D
 - VOL_VolumeMA25_SNZ
 - VOL_VolumeMA25_TSR_252D
cat_cols: