name: str_triple_barrier
feature_cols:
 - BET_Beta60_TSR_252D
 - BET_MarketHV20_CSZ
 - BET_MarketHV20_TSR_252D
 - BET_MarketReturn_CSZ
 - BET_MarketReturn_TSR_252D
 - BET_MarketTrendIdx_TSR_252D
 - BET_MarketVolChange_TSR_252D
 - BET_SectorMomentum5d_SNZ
 - BET_SectorMomentum5d_TSR_252D
 - BET_SectorRel_TSR_252D
 - BET_SectorRelStrength60_CSZ
 - BET_SectorRelStrength60_TSR_252D
 - CON_ProgressRate_SNZ
 - EVT_IsMissingEPS_CSZ
 - GOV_MarketSegment_SNZ
 - LIQ_TurnoverRatio_CSZ
 - MOM_High52wDist_SNZ
 - MOM_LinRegSlope10_CSR
 - MOM_Momentum12-1_SNZ
 - MOM_NewHighFlag3_TSR_252D
 - MOM_PricePos120_SNZ
 - MOM_Return12m_SNZ
 - MOM_Return6m_CSZ
 - QLT_EquityRatio_CSZ
 - QLT_EquityRatio_SNZ
 - QLT_OperatingProfitGrowthYOY_SNZ
 - QLT_OPMargin_SNZ
 - QLT_ROA_SNZ
 - QLT_ROE_SNZ
 - QLT_SalesGrowthYOY_SNZ
 - SPD_MarketForeignBuy_CSZ
 - SPD_MarketIndividualBuy_CSR
 - SPD_VWAPDev_CSR
 - SPD_VWAPDev_CSZ
 - VAL_EarningsYield_CSZ
 - VAL_LogPBR_CSZ
 - VAL_LogPBR_SNZ
 - VOL_ATRRatio_TSR_252D
 - VOL_DownsideDev60_CSZ
 - VOL_DownsideDev60_SNZ
 - VOL_DownsideDev60_TSR_252D
 - VOL_HistVol20_CSZ
 - VOL_HistVol20_SNZ
 - VOL_LargeMoveCount_CSZ
 - VOL_LargeMoveCount_TSR_252D
 - VOL_ReturnVolatility_TSR_252D
 - VOL_Volatility60_CSZ
 - VOL_VolumeMA25_CSZ
 - VOL_VolumeMA25_TSR_252D
cat_cols:
 - GOV_MarketSegment_SNZ