name: tac_rank
feature_cols:
 - BET_MarketHV20_CSZ
 - BET_MarketReturn_CSZ
 - BET_MarketTrendIdx_CSZ
 - BET_MarketVolChange_CSZ
 - BET_MarketVolChange_SNZ
 - BET_RelSectorReturn1d_SNZ
 - CON_RevisionRate_CSZ
 - EVT_EPSActual_CSZ
 - EVT_IsMissingEPS_RAW
 - GOV_MarketSegment_RAW
 - LIQ_TurnoverRatio_CSZ
 - MOM_DistHigh60_CSZ
 - MOM_DistSMA25-75_CSZ
 - MOM_DistSMA25-75_TSZ_20D
 - MOM_DistSMA5_TSZ_20D
 - MOM_GapRate_SNZ
 - MOM_LinRegSlope10_CSZ
 - MOM_LowerShadowMA5_SNZ
 - MOM_MACDHistDiff_TSZ_20D
 - MOM_MACDHistNorm_TSZ_20D
 - MOM_MADev200_CSZ
 - MOM_MADev75_SNZ
 - MOM_MaxGain5_TSZ_20D
 - MOM_Momentum12-1_SNZ
 - MOM_NewHighFlag3_CSZ
 - MOM_RCI26_TSZ_20D
 - MOM_RCI52_TSZ_20D
 - MOM_RCI9Diff_SNZ
 - MOM_RetIntraday_SNZ
 - MOM_Return1dLag2_SNZ
 - MOM_Return20d_CSZ
 - MOM_Return6m_CSZ
 - QLT_EquityRatio_CSZ
 - QLT_SalesGrowthYOY_SNZ
 - SEA_CosDayOfWeek_RAW
 - SEA_DayOfMonth_RAW
 - SEA_DayOfWeek_RAW
 - SEA_IsGotobi_RAW
 - SEA_IsMonthEnd_RAW
 - SEA_IsQuarterEnd_RAW
 - SEA_Quarter_RAW
 - SEA_SinDayOfWeek_RAW
 - SIZ_LogMarketCap_CSZ
 - SPD_DistVWAP5_CSZ
 - SPD_MarginBuyImpact_CSZ
 - SPD_MarginRatio_CSZ
 - SPD_MarketIndividualBuy_TSZ_20D
 - SPD_OverseaFlowTrend_CSZ
 - SPD_OverseaFlowTrend_TSZ_20D
 - SPD_VWAPDev_CSZ
 - VAL_EarningsYield_CSZ
 - VAL_EarningsYield_SNZ
 - VAL_LogPBR_CSZ
 - VAL_LogPBR_SNZ
 - VOL_ATRRatio_CSZ
 - VOL_ATRRatio_SNZ
 - VOL_HistVol20_CSZ
 - VOL_HV30_SNZ
 - VOL_LargeMoveCount_SNZ
 - VOL_RangeRatioLong_TSZ_20D
 - VOL_VolatilityParkinson_CSZ
 - VOL_VolumeMA25_SNZ
cat_cols:
 - GOV_MarketSegment_RAW
 - SEA_IsGotobi_RAW
 - SEA_IsMonthEnd_RAW
 - SEA_IsQuarterEnd_RAW