name: tac_DeepTabular
feature_cols:
- BET_Beta60_CSZ
- BET_Beta60_SNZ
- BET_MarketHV20_CSZ
- BET_MarketHV20_SNZ
- BET_MarketReturn_CSZ
- BET_MarketReturn_SNZ
- BET_MarketTrendIdx_CSZ
- BET_MarketTrendIdx_SNZ
- BET_MarketVolChange_CSZ
- BET_MarketVolChange_SNZ
- BET_RS25_CSZ
- BET_RS25_TSZ_20D
- BET_RelSectorReturn1d_SNZ
- BET_SectorMomentum5d_CSZ
- BET_SectorMomentum5d_SNZ
- BET_SectorRelStrength60_CSZ
- BET_SectorRelStrength60_SNZ
- BET_SectorRel_CSZ
- BET_SectorRel_TSZ_20D
- BET_SectorReturn_CSZ
- CON_RevisionRate_CSZ
- CON_RevisionRate_SNZ
- EVT_EPSActual_CSZ
- EVT_IsMissingEPS_RAW
- EVT_LogDaysSincePub_SNZ
- GOV_MarketSegment_RAW
- GOV_Sector33Code_RAW
- LIQ_AmihudIlliq_CSZ
- LIQ_AmihudIlliq_TSZ_20D
- LIQ_LogTradingCap_CSZ
- LIQ_TurnoverRatio_CSZ
- LIQ_VolSpikeCount20_CSZ
- MOM_DistHigh250_TSZ_20D
- MOM_DistHigh60_CSZ
- MOM_DistSMA25-75_CSZ
- MOM_DistSMA25-75_TSZ_20D
- MOM_DistSMA5_CSZ
- MOM_DistSMA5_TSZ_20D
- MOM_GapRate_SNZ
- MOM_GapRate_TSZ_20D
- MOM_High52wDist_CSZ
- MOM_High52wDist_SNZ
- MOM_LinRegSlope10_CSZ
- MOM_LowerShadowMA5_SNZ
- MOM_MACDHistDiff_SNZ
- MOM_MACDHistDiff_TSZ_20D
- MOM_MACDHistNorm_TSZ_20D
- MOM_MADev200_CSZ
- MOM_MADev25_CSZ
- MOM_MADev75_CSZ
- MOM_MADev75_SNZ
- MOM_MaxGain5_CSZ
- MOM_MaxGain5_TSZ_20D
- MOM_Momentum12-1_CSZ
- MOM_Momentum12-1_SNZ
- MOM_NewHighFlag3_CSZ
- MOM_NewHighFlag3_SNZ
- MOM_RCI26_TSZ_20D
- MOM_RCI52_SNZ
- MOM_RCI52_TSZ_20D
- MOM_RCI9Diff_SNZ
- MOM_RetIntraday_SNZ
- MOM_RetIntraday_TSZ_20D
- MOM_Return12m_CSZ
- MOM_Return12m_SNZ
- MOM_Return1dLag2_SNZ
- MOM_Return20d_CSZ
- MOM_Return20d_TSZ_20D
- MOM_Return3d_TSZ_20D
- MOM_Return5d_CSZ
- MOM_Return5d_TSZ_20D
- MOM_Return6m_CSZ
- MOM_Return6m_SNZ
- QLT_EquityRatio_CSZ
- QLT_OPMargin_SNZ
- QLT_OperatingProfitGrowthYOY_SNZ
- QLT_OperatingProfitGrowthYOY_TSZ_20D
- QLT_ROA_CSZ
- QLT_ROA_SNZ
- QLT_ROE_CSZ
- QLT_ROE_SNZ
- QLT_SalesGrowthYOY_CSZ
- QLT_SalesGrowthYOY_SNZ
- SEA_CosDayOfWeek_RAW
- SEA_SinDayOfWeek_RAW
- SEA_DayOfMonth_RAW
- SEA_DayOfWeek_RAW
- SEA_IsGotobi_RAW
- SEA_IsMonthEnd_RAW
- SEA_Quarter_RAW
- SEA_IsQuarterEnd_RAW
- SIZ_LogMarketCap_CSZ
- SPD_DistVWAP5_CSZ
- SPD_DistVWAP5_TSZ_20D
- SPD_DistVWAPSlope_CSZ
- SPD_FlowAccel_CSZ
- SPD_FlowAccel_TSZ_20D
- SPD_MarginBuyImpact_CSZ
- SPD_MarginRatio_CSZ
- SPD_MarketForeignBuy_CSZ
- SPD_MarketForeignBuy_TSZ_20D
- SPD_MarketIndividualBuy_CSZ
- SPD_MarketIndividualBuy_TSZ_20D
- SPD_OverseaFlowTrend_CSZ
- SPD_OverseaFlowTrend_TSZ_20D
- SPD_VWAPDev_CSZ
- SPD_VWAPDev_TSZ_20D
- VAL_EarningsYield_CSZ
- VAL_EarningsYield_SNZ
- VAL_LogPBR_CSZ
- VAL_LogPBR_SNZ
- VOL_ATRRatio_CSZ
- VOL_ATRRatio_SNZ
- VOL_ATRSqueezeBB_CSZ
- VOL_ATRSqueeze_TSZ_20D
- VOL_DownsideDev60_CSZ
- VOL_DownsideDev60_SNZ
- VOL_DownsideRun_SNZ
- VOL_GapAbs_TSZ_20D
- VOL_HV30_CSZ
- VOL_HV30_SNZ
- VOL_HVSlope_CSZ
- VOL_HVSlope_SNZ
- VOL_HistVol20_CSZ
- VOL_HistVol20_SNZ
- VOL_LargeMoveCount_CSZ
- VOL_LargeMoveCount_SNZ
- VOL_MAE5_TSZ_20D
- VOL_RangeRatioLong_TSZ_20D
- VOL_ReturnVolatility_CSZ
- VOL_ReturnVolatility_SNZ
- VOL_UlcerIndex14_CSZ
- VOL_UlcerIndex14_TSZ_20D
- VOL_VolRatioHV_TSZ_20D
- VOL_Volatility60_CSZ
- VOL_Volatility60_SNZ
- VOL_VolatilityParkinson_CSZ
- VOL_VolatilityParkinson_SNZ
- VOL_VolumeMA25_CSZ
- VOL_VolumeMA25_SNZ
cat_cols:
- EVT_IsMissingEPS_RAW
- GOV_MarketSegment_RAW
- GOV_Sector33Code_RAW
- SEA_DayOfMonth_RAW
- SEA_DayOfWeek_RAW
- SEA_IsGotobi_RAW
- SEA_IsMonthEnd_RAW
- SEA_Quarter_RAW
- SEA_IsQuarterEnd_RAW