
feature_cols:
- MOM_Return12m_RAW
- SPD_VWAPDev_CSZ
- GOV_MarketSegment_SNZ
- MOM_PricePos120_SNZ
- MOM_Return12m_TSZ_20D
- BET_SectorRelStrength60_RAW
- SPD_VWAPDev_RAW
- VOL_Volatility60_CSR
- QLT_SalesGrowthYOY_TSR_252D
- MOM_RCI52_TSR_252D
- VOL_HV30_TSR_252D
- VOL_Volatility60_CSZ
- BET_Beta60_TSZ_20D
- BET_SectorRelStrength60_TSR_252D
- EVT_LogDaysSincePub_RAW
- VOL_ATRRatio_CSZ
- EVT_LogDaysSincePub_CSR
- QLT_Accruals_TSR_252D
- SPD_VWAPDev_CSR
- QLT_SalesGrowthYOY_TSZ_20D
- SPD_MarginRatio_RAW
- BET_SectorRelStrength60_SNZ
- MOM_Return6m_SNZ
- LIQ_TurnoverRatio_CSR
- BET_Beta60_RAW
- BET_SectorMomentum5d_CSR
- VOL_ATRRatio_CSR
- MOM_Momentum12-1_RAW
- MOM_Return6m_RAW
- SPD_MarginBuyImpact_RAW
- VOL_DownsideDev60_TSR_252D
- VOL_VolumeMA25_SNZ
- CON_ProgressRate_TSR_252D
- MOM_Momentum12-1_TSR_252D
- BET_SectorMomentum5d_CSZ
- SPD_MarginRatio_CSR
- MOM_PricePos120_RAW
- BET_SectorRelStrength60_CSZ
- VOL_VolumeMA25_TSR_252D
- MOM_DistSMA75_RAW
- MOM_MADev75_RAW
- SPD_MarginRatio_CSZ
- BET_RelSectorReturn5d_RAW
- LIQ_VolUpDownRatio_TSZ_20D
- MOM_PricePos120_CSZ
- BET_Beta60_CSZ
- VOL_RealizedSkew20_TSR_252D
- BET_Beta60_CSR
- QLT_OperatingProfitGrowthYOY_TSR_252D
- CON_ProgressRate_CSR
- SEA_DayOfMonth_RAW
- MOM_NewHighFlag3_TSR_252D
- LIQ_AmihudIlliq_CSZ
- LIQ_VolSpikeCount20_TSR_252D
- VOL_VolatilityParkinson_CSZ
- MOM_MADev200_RAW
- QLT_ROA_CSZ
- CON_ProgressRate_SNZ
- MOM_DistSMA25-75_TSZ_20D
- QLT_ROA_RAW
- VOL_ReturnKurtosis_TSZ_20D
- MOM_DistHigh60_CSZ
- MOM_RCI26_TSR_252D
- MOM_RCI52_CSZ
- BET_RS25_CSZ
- VAL_LogPBR_TSR_252D
- CON_ProgressRate_RAW
- EVT_LogDaysSincePub_CSZ
- MOM_GapRate_TSR_252D
- VAL_LogPBR_CSZ
- VAL_EarningsYield_CSR
- SPD_MarginBuyImpact_CSZ
- VAL_LogPBR_RAW
- BET_Beta60_SNZ
- MOM_RCI52_CSR
- VOL_DownsideDev60_CSR
- QLT_EquityRatio_TSR_252D
- VOL_DownsideDev60_CSZ
- BET_MarketHV20_RAW
- MOM_RCI52_RAW
- MOM_DistHigh250_RAW
- QLT_OperatingProfitGrowthYOY_TSZ_20D
- MOM_DistHigh60_CSR
- MOM_Return20d_CSZ
- VOL_Volatility60_RAW
- LIQ_TurnoverRatio_RAW
- MOM_DistSMA25-75_RAW
- BET_SectorMomentum5d_SNZ
- GOV_MarketSegment_CSR
- VOL_HistVol20_TSR_252D
- MOM_RCI52_SNZ
- MOM_Return12m_TSR_252D
- MOM_IchimokuDist_RAW
- QLT_OPMargin_TSR_252D
- QLT_ROA_TSR_252D
- MOM_High52wDist_RAW
- MOM_Return12m_CSR
- BET_SectorRelStrength60_TSZ_20D
- CON_RevisionRate_SNZ
- VOL_HV30_CSZ
- BET_SectorRelStrength60_CSR
- SPD_OverseaFlowTrend_TSR_252D
- LIQ_VolumeLog_RAW
- EVT_IsMissingEPS_CSZ
- BET_RelSectorReturn5d_CSZ
- CON_RevisionRate_CSR
- QLT_OperatingProfitGrowthYOY_CSR
- LIQ_TurnoverRatio_CSZ
- QLT_ROE_CSR
- CON_RevisionRate_CSZ
- SPD_OverseaFlowTrend_CSZ
- VOL_HistVol20_CSR
- SEA_TimeIdx_RAW
- SPD_MarketIndividualBuy_RAW
- VAL_EarningsYield_SNZ
- MOM_MaxGain5_CSZ
- VOL_VolatilityParkinson_CSR
- MOM_Momentum12-1_TSZ_20D
- VOL_ATRRatio_RAW
- MOM_DistSMA25-75_TSR_252D
- MOM_RCI26_SNZ
- SPD_OverseaFlowTrend_RAW
- MOM_Return12m_CSZ
- QLT_ROA_CSR
- SPD_FlowAccel_CSZ
- GOV_MarketSegment_RAW
- QLT_EPSGrowthYOY_RAW
- MOM_High52wDist_SNZ
- VOL_ATRSqueezeBB_TSR_252D
- VOL_HVSlope_CSZ
- SPD_MarketIndividualBuy_TSR_252D
- QLT_ROE_CSZ
- QLT_SalesGrowthYOY_RAW
- MOM_ClosePosition_CSZ
- VOL_HV30_CSR
- QLT_ROE_RAW
- BET_RS25_TSR_252D
- SPD_FlowAccel_CSR
- QLT_ROE_SNZ
- QLT_Accruals_RAW
- VAL_EarningsYield_RAW
- BET_SectorMomentum5d_TSZ_20D
- VOL_RealizedSkew20_RAW
- CON_ProgressRate_TSZ_20D
- EVT_IsMissingEPS_CSR
- SPD_MarketForeignBuy_RAW
- VOL_RealizedSkew20_TSZ_20D
- MOM_Return6m_TSZ_20D
- EVT_EPSActual_SNZ
- SPD_OverseaFlowTrend_CSR
- EVT_IsMissingEPS_SNZ
- SEA_MonthInQuarter_RAW
- BET_MarketTrendIdx_RAW
- MOM_MACDHistNorm_RAW
- VOL_HVSlope_CSR
- SEA_IsQuarterEnd_RAW
- VAL_LogPBR_CSR
- VOL_RealizedSkew20_CSR
- MOM_LinRegSlope10_SNZ
- VOL_ATRRatio_SNZ
- VOL_RealizedSkew20_CSZ
- VOL_VolatilityParkinson_TSZ_20D
- CON_RevisionRate_TSZ_20D
- SPD_MarginBuyImpact_CSR
- VAL_EarningsYield_CSZ
- VOL_HV30_RAW
- QLT_EPSGrowthYOY_CSR
- MOM_DistHigh60_RAW
- EVT_LogDaysSincePub_SNZ
- SPD_MarginBuyImpact_TSR_252D
- VOL_HistVol20_CSZ
- VOL_ReturnVolatility_TSR_252D
- SIZ_LogMarketCap_CSZ
- VOL_VolatilityParkinson_RAW
- SPD_MarginRatioDelta4w_TSR_252D