feature_cols:
- VAL_LogPBR_CSZ
- VOL_HV30_CSZ
- MOM_DistSMA25-75_RAW
- BET_Beta60_RAW
- SPD_MarginRatio_RAW
- SPD_VWAPDev_RAW
- SPD_MarginBuyImpact_RAW
- VAL_LogPBR_SNZ
- SPD_VWAPDev_CSZ
- VOL_MAE5_CSZ
- MOM_DistHigh60_CSZ
- VOL_VolatilityParkinson_CSZ
- LIQ_TurnoverRatio_CSZ
- SIZ_LogMarketCap_RAW
- VOL_VolatilityParkinson_TSR_252D
- VAL_EarningsYield_CSZ
- VOL_DownsideDev60_RAW
- MOM_DistHigh250_RAW
- VOL_HV30_RAW
- QLT_EPSGrowthYOY_CSZ
- MOM_NewHighFlag3_TSR_252D
- QLT_EquityRatio_RAW
- VOL_DownsideDev60_SNZ
- VOL_ATRRatio_TSZ_20D
- QLT_OPMargin_TSR_252D
- EVT_EPSActual_CSZ
- MOM_Return12m_TSR_252D
- MOM_PricePos120_SNZ
- EVT_LogDaysSincePub_SNZ
- CON_RevisionRate_SNZ
- QLT_ROA_SNZ
- MOM_DistHigh250_SNZ
- MOM_DistHigh250_TSR_252D
- QLT_Accruals_SNZ
- BET_SectorRelStrength60_TSZ_20D
- CON_ProgressRate_CSR
- VOL_LargeMoveCount_RAW
- BET_SectorMomentum5d_CSR
- VOL_DownsideDev60_TSR_252D
- QLT_SalesGrowthYOY_CSZ
- GOV_MarketSegment_RAW
- GOV_Sector33Code_RAW
- SEA_DayOfMonth_RAW
- SEA_IsQuarterEnd_RAW
- SEA_Quarter_RAW
cat_cols:
- GOV_MarketSegment_RAW
- GOV_Sector33Code_RAW
- SEA_DayOfMonth_RAW
- SEA_IsQuarterEnd_RAW
- SEA_Quarter_RAW