name: gandalf_tac_rank
feature_cols:
 - BET_MarketReturn_SNZ
 - BET_MarketTrendIdx_CSZ
 - BET_SectorRelStrength60_CSZ
 - BET_SectorReturn_CSZ
 - EVT_EPSActual_CSZ
 - GOV_MarketSegment_RAW
 - GOV_Sector33Code_RAW
 - LIQ_AmihudIlliq_CSZ
 - LIQ_VolSpikeCount20_CSZ
 - MOM_GapRate_TSZ_20D
 - MOM_High52wDist_SNZ
 - MOM_MADev200_CSZ
 - MOM_MaxGain5_CSZ
 - MOM_MaxGain5_TSZ_20D
 - MOM_Momentum12-1_CSZ
 - MOM_NewHighFlag3_SNZ
 - MOM_RetIntraday_TSZ_20D
 - MOM_Return12m_CSZ
 - MOM_Return1dLag2_SNZ
 - MOM_Return20d_TSZ_20D
 - QLT_OPMargin_SNZ
 - QLT_ROE_CSZ
 - SEA_IsQuarterEnd_RAW
 - SPD_DistVWAPSlope_CSZ
 - SPD_FlowAccel_TSZ_20D
 - SPD_MarginBuyImpact_CSZ
 - SPD_MarginRatio_CSZ
 - SPD_MarketForeignBuy_TSZ_20D
 - SPD_MarketIndividualBuy_CSZ
 - VOL_ATRRatio_CSZ
 - VOL_DownsideRun_SNZ
 - VOL_HV30_SNZ
 - VOL_HVSlope_SNZ
 - VOL_ReturnVolatility_SNZ
 - VOL_UlcerIndex14_CSZ
 - VOL_UlcerIndex14_TSZ_20D
 - VOL_Volatility60_SNZ
 - VOL_VolRatioHV_TSZ_20D
 - VOL_VolumeMA25_CSZ
cat_cols:
 - GOV_MarketSegment_RAW
 - GOV_Sector33Code_RAW
 - SEA_IsQuarterEnd_RAW