feature_cols:
  - VAL_LogPBR_CSZ
  - LIQ_TurnoverRatio_CSZ
  - MOM_NewHighFlag3_TSR_252D
  - MOM_DistHigh250_SNZ
  - CON_RevisionRate_CSR
  - MOM_MACDHistNorm_CSZ
  - QLT_SalesGrowthYOY_CSZ
  - MOM_MADev75_SNZ
  - VOL_DownsideDev60_CSZ
  - EVT_EPSActual_CSZ
  - MOM_Return5d_CSZ
  - CON_RevisionRate_TSR_252D
  - LIQ_VolSpikeCount20_CSR
  - VOL_Volatility60_SNZ
  - VOL_MAE10_CSZ
  - MOM_Return12m_SNZ
  - MOM_ADX14_CSR
  - MOM_MADev200_SNZ
  - MOM_RCI52_TSR_252D
  - VOL_HV30_TSR_252D
  - MOM_ClosePosition_TSR_252D
  - VOL_VolumeMA25_SNZ
  - BET_SectorRelStrength60_TSR_252D
  - CON_RevisionRate_SNZ
  - VOL_ReturnVolatility_SNZ
  - LIQ_VolSpikeCount20_TSR_252D
  - QLT_ROA_SNZ
  - QLT_Accruals_TSR_252D
  - VOL_RealizedSkew20_TSR_252D
  - MOM_NewHighFlag3_CSZ
  - CON_ProgressRate_SNZ
  - MOM_Return12m_TSZ_20D
  - MOM_GapRate_TSR_252D
  - MOM_RetIntraday_TSR_252D
  - SPD_MarginBuyImpact_TSR_252D
  - QLT_OperatingProfitGrowthYOY_TSR_252D
  - VOL_VolumeMA25_CSR
  - MOM_ADX14_TSZ_20D
  - VOL_VolatilityParkinson_TSZ_20D
  - SPD_MarginRatioDelta4w_RAW
  - MOM_NewHighFlag3_SNZ
  - MOM_Return1dLag1_TSR_252D
  - VOL_VolRatioHV_TSR_252D
  - SPD_VWAPDev_TSR_252D
  - BET_SectorRelStrength60_CSR
  - MOM_RCI26Diff_CSR
  - QLT_OPMargin_SNZ
  - VOL_UlcerIndex14_TSR_252D
  - SPD_MarginBuyImpact_CSZ
  - GOV_MarketSegment_RAW
  - GOV_Sector33Code_RAW
  - SEA_DayOfMonth_RAW
  - SEA_IsQuarterEnd_RAW
  - SEA_Quarter_RAW
cat_cols:
  - GOV_MarketSegment_RAW
  - GOV_Sector33Code_RAW
  - SEA_DayOfMonth_RAW
  - SEA_IsQuarterEnd_RAW
  - SEA_Quarter_RAW