name: str_TabNet
feature_cols:
- BET_Beta60_SNZ
- BET_Beta60_TSR_252D
- BET_MarketHV20_SNZ
- BET_MarketHV20_TSR_252D
- BET_MarketReturn_CSZ
- BET_MarketReturn_TSR_252D
- BET_MarketTrendIdx_CSZ
- BET_MarketTrendIdx_TSR_252D
- BET_MarketVolChange_CSZ
- BET_MarketVolChange_TSR_252D
- BET_SectorMomentum5d_SNZ
- BET_SectorMomentum5d_TSR_252D
- BET_SectorRelStrength60_SNZ
- BET_SectorRelStrength60_TSR_252D
- BET_SectorRel_SNZ
- BET_SectorRel_TSR_252D
- BET_SectorReturn_SNZ
- BET_SectorReturn_TSR_252D
- CON_ProgressRate_SNZ
- CON_ProgressRate_TSR_252D
- CON_RevisionRate_CSZ
- CON_RevisionRate_SNZ
- EVT_EPSActual_CSZ
- EVT_EPSActual_SNZ
- EVT_IsMissingEPS_CSZ
- EVT_IsMissingEPS_SNZ
- GOV_MarketSegment_CSZ
- GOV_MarketSegment_SNZ
- LIQ_AmihudIlliq_CSZ
- LIQ_LogTradingCap_CSZ
- LIQ_TurnoverRatio_CSZ
- MOM_DistHigh60_CSZ
- MOM_DistSMA25-75_CSZ
- MOM_High52wDist_SNZ
- MOM_High52wDist_TSR_252D
- MOM_MADev200_CSZ
- MOM_MADev200_SNZ
- MOM_MADev75_CSZ
- MOM_Momentum12-1_SNZ
- MOM_Momentum12-1_TSR_252D
- MOM_NewHighFlag3_SNZ
- MOM_NewHighFlag3_TSR_252D
- MOM_PricePos120_SNZ
- MOM_Return12m_SNZ
- MOM_Return12m_TSR_252D
- MOM_Return6m_CSZ
- QLT_Accruals_SNZ
- QLT_Accruals_TSR_252D
- QLT_EPSGrowthYOY_SNZ
- QLT_EPSGrowthYOY_TSR_252D
- QLT_EquityRatio_CSZ
- QLT_EquityRatio_SNZ
- QLT_OPMargin_SNZ
- QLT_OPMargin_TSR_252D
- QLT_OperatingProfitGrowthYOY_SNZ
- QLT_OperatingProfitGrowthYOY_TSR_252D
- QLT_ROA_CSZ
- QLT_ROA_SNZ
- QLT_ROE_SNZ
- QLT_ROE_TSR_252D
- QLT_SalesGrowthYOY_SNZ
- QLT_SalesGrowthYOY_TSR_252D
- SEA_CosDayOfWeek_RAW
- SEA_SinDayOfWeek_RAW
- SIZ_LogMarketCap_CSZ
- SPD_FlowAccel_CSZ
- SPD_FlowAccel_TSR_252D
- SPD_MarginBuyImpact_CSZ
- SPD_MarginRatio_CSZ
- SPD_MarketForeignBuy_CSZ
- SPD_MarketForeignBuy_TSR_252D
- SPD_MarketIndividualBuy_CSZ
- SPD_MarketIndividualBuy_TSR_252D
- SPD_OverseaFlowTrend_CSZ
- SPD_OverseaFlowTrend_TSR_252D
- SPD_VWAPDev_CSZ
- VAL_EarningsYield_CSZ
- VAL_EarningsYield_SNZ
- VAL_LogPBR_SNZ
- VAL_LogPBR_TSR_252D
- VOL_ATRRatio_SNZ
- VOL_ATRRatio_TSR_252D
- VOL_ATRSqueeze_SNZ
- VOL_DownsideDev60_SNZ
- VOL_DownsideDev60_TSR_252D
- VOL_HV30_CSZ
- VOL_HV30_TSR_252D
- VOL_HistVol20_SNZ
- VOL_HistVol20_TSR_252D
- VOL_LargeMoveCount_CSZ
- VOL_LargeMoveCount_TSR_252D
- VOL_ReturnVolatility_TSR_252D
- VOL_Volatility60_SNZ
- VOL_Volatility60_TSR_252D
- VOL_VolatilityParkinson_SNZ
- VOL_VolatilityParkinson_TSR_252D
- VOL_VolumeMA25_SNZ
- VOL_VolumeMA25_TSR_252D
cat_cols:
- EVT_IsMissingEPS_RAW
- GOV_market_segment_RAW
- GOV_sector33_code_RAW
- SEA_DayOfMonth_RAW
- SEA_DayOfWeek_RAW
- SEA_IsGotobi_RAW
- SEA_IsMonthEnd_RAW
- SEA_Quarter_RAW
- SEA_IsQuarterEnd_RAW

