name: str_TimeSeries
feature_cols:
- BET_Beta60_RAW
- BET_Beta60_TSR_252D
- BET_MarketHV20_RAW
- BET_MarketHV20_TSR_252D
- BET_MarketReturn_TSR_252D
- BET_MarketTrendIdx_TSR_252D
- BET_MarketVolChange_TSR_252D
- BET_SectorMomentum5d_TSR_252D
- BET_SectorRelStrength60_RAW
- BET_SectorRelStrength60_TSR_252D
- BET_SectorRel_RAW
- BET_SectorRel_TSR_252D
- BET_SectorReturn_TSR_252D
- CON_ProgressRate_RAW
- CON_ProgressRate_TSR_252D
- GOV_MarketSegment_RAW
- GOV_Sector33Code_RAW
- MOM_High52wDist_TSR_252D
- MOM_IchimokuDist_RAW
- MOM_LinRegSlope10_RAW
- MOM_MADev200_RAW
- MOM_MADev75_RAW
- MOM_Momentum12-1_RAW
- MOM_Momentum12-1_TSR_252D
- MOM_NewHighFlag3_TSR_252D
- MOM_Return12m_TSR_252D
- QLT_Accruals_TSR_252D
- QLT_EPSGrowthYOY_TSR_252D
- QLT_OPMargin_TSR_252D
- QLT_OperatingProfitGrowthYOY_TSR_252D
- QLT_ROE_RAW
- QLT_ROE_TSR_252D
- QLT_SalesGrowthYOY_RAW
- QLT_SalesGrowthYOY_TSR_252D
- SEA_Quarter_RAW
- SEA_TimeIdx_RAW
- SPD_FlowAccel_TSR_252D
- SPD_MarketForeignBuy_RAW
- SPD_MarketForeignBuy_TSR_252D
- SPD_MarketIndividualBuy_RAW
- SPD_MarketIndividualBuy_TSR_252D
- SPD_OverseaFlowTrend_RAW
- SPD_OverseaFlowTrend_TSR_252D
- SPD_VWAPDev_RAW
- VAL_LogPBR_TSR_252D
- VOL_ATRRatio_RAW
- VOL_ATRRatio_TSR_252D
- VOL_ATRSqueezeBB_RAW
- VOL_DownsideDev60_RAW
- VOL_DownsideDev60_TSR_252D
- VOL_HV30_RAW
- VOL_HV30_TSR_252D
- VOL_HistVol20_RAW
- VOL_HistVol20_TSR_252D
- VOL_LargeMoveCount_TSR_252D
- VOL_MAE10_RAW
- VOL_ReturnVolatility_TSR_252D
- VOL_UlcerIndex14_RAW
- VOL_Volatility60_RAW
- VOL_Volatility60_TSR_252D
- VOL_VolatilityParkinson_RAW
- VOL_VolatilityParkinson_TSR_252D
- VOL_VolumeMA25_TSR_252D
cat_cols:
- GOV_MarketSegment_RAW
- GOV_Sector33Code_RAW
- SEA_Quarter_RAW