feature_cols:
- SPD_VWAPDev_CSZ
- BET_Beta60_RAW
- MOM_NewHighFlag3_TSR_252D
- SPD_MarginRatio_CSR
- BET_SectorRelStrength60_RAW
- MOM_RCI52_TSR_252D
- SIZ_LogMarketCap_CSZ
- VAL_LogPBR_RAW
- BET_SectorMomentum5d_CSR
- SPD_MarginBuyImpact_CSZ
- VOL_Volatility60_RAW
- MOM_ClosePosition_CSZ
- VOL_VolumeMA25_SNZ
- MOM_RCI26_TSR_252D
- QLT_SalesGrowthYOY_TSR_252D
- QLT_OperatingProfitGrowthYOY_TSR_252D
- MOM_Return12m_CSR
- QLT_Accruals_TSR_252D
- MOM_High52wDist_SNZ
- MOM_PricePos120_SNZ
- MOM_RCI52_CSZ
- MOM_Momentum12-1_RAW
- CON_ProgressRate_RAW
- VOL_HVSlope_CSZ
- LIQ_VolSpikeCount20_TSR_252D
- VOL_HV30_TSR_252D
- MOM_DistSMA75_RAW
- CON_RevisionRate_CSZ
- MOM_Return20d_CSZ
- QLT_SalesGrowthYOY_RAW
- BET_SectorMomentum5d_SNZ
- SPD_VWAPDev_CSR
- BET_Beta60_TSZ_20D
cat_cols: