name: str_gauss_rank
feature_cols:
 - BET_MarketHV20_SNZ
 - BET_MarketReturn_TSR_252D
 - BET_MarketVolChange_TSR_252D
 - BET_SectorRel_SNZ
 - BET_SectorRel_TSR_252D
 - BET_SectorReturn_SNZ
 - CON_ProgressRate_TSR_252D
 - EVT_EPSActual_SNZ
 - GOV_MarketSegment_SNZ
 - LIQ_TurnoverRatio_CSZ
 - MOM_DistSMA25-75_CSZ
 - MOM_High52wDist_SNZ
 - MOM_High52wDist_TSR_252D
 - MOM_MADev75_CSZ
 - MOM_Return12m_SNZ
 - MOM_Return12m_TSR_252D
 - QLT_EPSGrowthYOY_TSR_252D
 - QLT_EquityRatio_SNZ
 - QLT_OperatingProfitGrowthYOY_TSR_252D
 - QLT_ROA_CSZ
 - QLT_ROE_TSR_252D
 - SEA_CosDayOfWeek_RAW
 - SEA_SinDayOfWeek_RAW
 - SIZ_LogMarketCap_CSZ
 - SPD_FlowAccel_CSZ
 - SPD_FlowAccel_TSR_252D
 - SPD_MarketForeignBuy_CSZ
 - SPD_MarketIndividualBuy_CSZ
 - SPD_VWAPDev_CSZ
 - VAL_EarningsYield_CSZ
 - VAL_LogPBR_SNZ
 - VAL_LogPBR_TSR_252D
 - VOL_ATRRatio_TSR_252D
 - VOL_ATRSqueeze_SNZ
 - VOL_DownsideDev60_TSR_252D
 - VOL_Volatility60_SNZ
 - VOL_Volatility60_TSR_252D
 - VOL_VolatilityParkinson_SNZ
 - VOL_VolumeMA25_TSR_252D
cat_cols:
 - GOV_MarketSegment_SNZ