name: "str_candidates"
feature_cols: [
  'ADX_14',
  'Dist_SMA5',
  'Dist_SMA25',
  'Dist_SMA75',
  'Dist_VWAP_5',
  'vwap_dev',
  'LinReg_Slope_10',
  'MACD_Hist_Norm',
  'MAE_5',
  'MAE_10',
  'Dist_High_60',
  'Dist_High_250',
  'Dist_Kijun',
  'New_High_Flag_3',
  'ichimoku_dist',
  'Log_Return',
  'Downside_Run',
  'Return_5d',
  'Return_10d',
  'Return_20d',
  'BB_Bandwidth',
  'Upper_Shadow_Ratio',
  'Intraday_Strength',
  'Streak',
  'Close_Position',
  'Gap_Rate',
  'Large_Move_Count',
  'Range_Ratio_Long',
  'Max_Gain_5',
  'RCI_9',
  'RCI_26_Diff',
  'RCI_52',
  'Streak',
  'momentum_12_1',
  'ret_intraday',
  'ATR_Ratio',
  'ATR_Squeeze',
  'ATR_Squeeze_bb',
  'hist_vol_20',
  'HV_30',
  'HV_Slope',
  'Ulcer_Index_14',
  'atr_chg_rate',
  'Volume_Log',
  'Volume_Slope_5',
  'Log_Trading_Cap',
  'Volatility_Parkinson',
  'Return_Volatility',
  'Vol_Up_Down_Ratio',
  'Volume_MA_25',
  'turnover_ratio',
  'amihud_illiq',
  'EPS_Actual',
  'log_days_since_pub',
  'log_market_cap',
  'sales_growth_yoy',
  'DayOfMonth',
  'DayOfWeek',
  'Sin_DayOfWeek',
  'Cos_DayOfWeek',
  'Quarter',
  'Is_Quarter_End',
  'time_idx',
  'Beta_60',
  'RS_25',
  'Market_Return',
  'Market_Trend_Idx',
  'Market_HV_20',
  'market_segment',
  'market_vol_change',
  'margin_buy_impact',
  'margin_ratio',
  'Sector_Momentum_5d',
  'sector_return',
  'sector33_code',
  'Sector_Rel',
  'Rel_Sector_Return_1d',
  'Rel_Sector_Return_5d',
  'sector_short_sell_ratio',
  'accruals_sector_z',
  'eps_growth_yoy_sector_z',
  'equity_ratio_sector_z',
  'log_pbr_sector_z',
  'earnings_yield_sector_z',
  'operating_profit_growth_yoy_sector_z',
  'op_margin_sector_z',
  'roa_sector_z',
  'roe_sector_z',
  'sales_growth_yoy_sector_z',
  'revision_rate_sector_z',
  'ATR_Ratio_sector_z',
  'ma_dev_25_sector_z',
  'ma_dev_200_sector_z',
  'Return_6m_sector_z',
  'Return_12m_sector_z',
  'high_52w_dist_sector_z',
  'downside_dev_60_sector_z',
  'volatility_60_sector_z',
  'margin_ratio_sector_z',
  'margin_buy_impact_sector_z',
  'Market_Foreign_Z_250',
  'Market_Foreign_Z_60',
  'Market_Individual_Z_250',
  'Market_Individual_Z_60',
  'Market_Foreign_Diff',
  'overseas_flow_trend',
  'flow_accel',
]
cat_cols: [
  'DayOfMonth',
  'DayOfWeek',
  'Quarter',
  'Is_Quarter_End',
  'market_segment',
  'sector33_code',
]