
# 例: config/model/elasticnet.yaml
name: elasticnet
group: linear
data_category: tabular

preprocessor_target: src.preprocess.preprocess_elasticnet.ElasticNetPreprocessor
model_target: src.models.elasticnet_wrapper.ElasticNetWrapper
