# config/model/gandalf.yaml
name: "GANDALF"
_target_: "gandalf.GANDALFRegressor"
# ハイパーパラメータ以外でモデル構造に依存する設定
# 前処理クラスのパスを記述（後述のスクリプトで動的ロード）
preprocessor_target: "src.preprocess.preprocess_gandalf.GANDALFPreprocessor"
model_target: "src.models.gandalf_wrapper.GANDALFWrapper"
# このモデルが必要とするデータ種別（data/フォルダの設定と紐付け）
data_category: "tabular"
ensemble_size: 1
