# [不変レイヤー] LGBM共通の基盤設定
learning_rate: 0.005
feature_fraction: 0.8
bagging_fraction: 0.8
lambda_l1: 1.0
lambda_l2: 1.0
seed: 42

# 学習プロトコル
num_boost_round: 1000
is_unbalance: true
use_time_decay: false
time_decay_rate: 0.9999
bagging_freq: 6
patience: 150
verbose: -1
