# config/period/str_standard.yaml
purge_days: 60
embargo_days: 90
pct_embargo: 0.01       # データの長さに対するエンバーゴの割合
n_splits: 5             # 分割数
n_test_chunks: 2        # CPCVでのテストチャンク数
valid_start_date: "2024-01-01"
test_start_date: "2025-01-01"