# @package _global_
# ElasticNet STR Risk スイープ
defaults:
  - override /hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
      multivariate: true
      n_startup_trials: 30
    direction: maximize
    storage: "sqlite:///optuna.db"
    n_trials: 50
    params:
      hparams.l1_ratio: interval(0.01, 0.4)
      hparams.alpha: tag(log, interval(1e-5, 1e-1))
