# @package _global_
defaults:
  - override /hydra/sweeper: optuna
hydra:
  sweeper:
    # Optunaの設定
    sampler:
      _target_: src.utils.samplers.HydraBruteForceSampler
    storage: "sqlite:///optuna.db"
    n_trials: 32
    params:
      hparams.n_blocks: choice(1,2,3,4)
      hparams.d_token: choice(8,16,32,64)
      hparams.attention_dropout: choice(0.0, 0.1)
      # 1. 学習率（バッチサイズ拡大に伴い上限を少し広げる）
      hparams.lr: 0.0001
      hparams.attention_n_heads: 4
      hparams.ffn_dropout: 0.1
      hparams.residual_dropout: 0.1
      hparams.head_dropout: 0.1
      hparams.weight_decay: 1e-5
      hparams.batch_size: 512
      hparams.max_epochs: 10
      hparams.patience: 3