# @package _global_
# Step 2: TAC Risk (FT-Transformer) ラフチューニング
defaults:
  - override /hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      _target_: src.utils.samplers.HydraBruteForceSampler
    storage: "sqlite:///optuna.db"
    direction: maximize
    n_trials: 12
    params:
      ++hparams.d_token: choice(8, 16, 32)
      ++hparams.n_blocks: choice(1, 2)
      ++hparams.attention_dropout: choice(0.3, 0.4)
      
      ++hparams.lr: 0.0001
      ++hparams.attention_n_heads: 2
