# @package _global_
defaults:
  - override /hydra/sweeper: optuna
interval:
  tac: 15
  str: 40
hydra:
  sweeper:
    # Optunaの設定
    sampler:
      _target_: src.utils.samplers.HydraBruteForceSampler
      seed: 42
    direction: maximize  # ランクICやシャープレシオの最大化
    n_trials: 6         # 計算負荷と探索効率のバランス（まずは50回）
    params:
      hparams.gflu_stages: choice(4, 6, 10)
      hparams.head_hidden_dims: choice("[64]", "[128, 64]")
      hparams.learning_rate: 0.0004
      hparams.gflu_feature_init_sparsity: 0.1
      hparams.weight_decay: 0.001
      hparams.batch_size: 1024
      hparams.max_epochs: 30
      hparams.patience: 3