# @package _global_
defaults:
  - override /hydra/sweeper: optuna
interval:
  tac: 10
  str: 30
hydra:
  sweeper:
    # Optunaの設定
    sampler:
      _target_: src.utils.samplers.HydraBruteForceSampler
      seed: 42
    direction: maximize  # Sharpe Ratioなどを最大化
    n_trials: 18        # 試行回数
    params:
      hparams.learning_rate: choice(0.05, 0.1)
      hparams.num_leaves: choice(15, 31, 63)
      hparams.min_child_samples: choice(200, 500, 1000)
      # 固定値
      hparams.max_depth: -1
      hparams.feature_fraction: 0.8
      hparams.bagging_fraction: 0.8
      hparams.bagging_freq: 5
      hparams.lambda_l1: 1.0
      hparams.lambda_l2: 1.0
      hparams.verbose: -1