# @package _global_
# Step 2: STR Alpha (LGBM) ラフチューニング
defaults:
  - override /hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      _target_: src.utils.samplers.HydraBruteForceSampler
    storage: "sqlite:///optuna.db"
    direction: maximize
    n_trials: 27
    params:
      ++hparams.num_leaves: choice(3, 7, 15)
      ++hparams.max_depth: choice(2, 3, 4)
      ++hparams.min_child_samples: choice(2000, 4000, 8000)
