# @package _global_
# Step 2: STR Risk (LGBM) ラフチューニング
defaults:
  - override /hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      _target_: src.utils.samplers.HydraBruteForceSampler
    storage: "sqlite:///optuna.db"
    direction: maximize
    n_trials: 18
    params:
      ++hparams.num_leaves: choice(2, 3, 5)
      ++hparams.max_depth: choice(1, 2)
      ++hparams.min_child_samples: choice(4000, 8000, 12000)
