# @package _global_
defaults:
  - override /hydra/sweeper: optuna
hydra:
  sweeper:
    # Optunaの設定
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
      multivariate: true
    direction: maximize  # Sharpe Ratioなどを最大化
    n_trials: 3       # 最適化のため試行回数を増加
    params:
      # 探索空間を広く定義し、ベイズ最適化（TPE）を適用
      hparams.learning_rate: tag(log, interval(0.001, 0.03))
      hparams.feature_fraction: interval(0.5, 0.9)
      hparams.lambda_l1: tag(log, interval(0.1, 100.0))
      hparams.lambda_l2: tag(log, interval(0.1, 100.0))
      # 固定値
      hparams.max_depth: -1
      hparams.verbose: -1