# @package _global_
# Step 2: TAC Alpha (LGBM) ラフチューニング
defaults:
  - override /hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      _target_: src.utils.samplers.HydraBruteForceSampler
    storage: "sqlite:///optuna.db"
    direction: maximize
    n_trials: 2
    params:
      ++hparams.num_leaves: choice(15)
      ++hparams.max_depth: choice(4)
      ++hparams.min_child_samples: choice(1500,2000)
      ++hparams.learning_rate: 0.01
