# @package _global_
defaults:
  - override /hydra/sweeper: optuna
interval:
  tac: 15
  str: 40
hydra:
  sweeper:
    # Optunaの設定
    sampler:
      _target_: src.utils.samplers.HydraBruteForceSampler
      seed: 42
    direction: maximize  # ランクICやシャープレシオの最大化
    n_trials: 8        # DL系は学習時間が長いため、まずは100回程度
    params:
      hparams.n_d: choice(8, 16)
      hparams.n_a: 24
      hparams.n_steps: choice(3, 5)
      hparams.n_independent: choice(2,4)
      hparams.gamma: 1.2
      hparams.optimizer_params.lr: 0.02
      hparams.lambda_sparse: 1e-4
      hparams.n_shared: 2
      hparams.max_epochs: 30
      hparams.patience: 3
      hparams.use_pretrain: False