# @package _global_
defaults:
  - override /hydra/sweeper: optuna
hydra:
  sweeper:
    sampler:
      _target_: src.utils.samplers.HydraBruteForceSampler
    storage: "sqlite:///optuna.db"
    n_trials: 54
    params:
      # --- アーキテクチャ・アンカー (Grid Search) ---
      hparams.n_layers: choice(2, 3, 4)
      hparams.num_channel: choice(8, 16, 32)
      hparams.kernel_size: choice(3, 5)
      # --- 学習の安定化用固定値 (ノイズを排除) ---
      hparams.lr: 0.0001
      hparams.weight_decay: 1e-4
      hparams.batch_size: 1024
      # 固定値
      hparams.max_epochs: 150
      hparams.patience: 15        # ema_alpha = 0.33 (過去のスコアに約67%の重みを置く平滑化)に対応できる長さに設定
