# @package _global_
# Step 2: STR Risk (TCN) ラフチューニング
defaults:
  - override /hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      _target_: src.utils.samplers.HydraBruteForceSampler
    storage: "sqlite:///optuna.db"
    direction: maximize
    n_trials: 24
    params:
      ++hparams.num_channel: choice(2, 4, 8)
      ++hparams.n_layers: choice(3, 4)
      ++hparams.kernel_size: choice(5, 7)
      ++hparams.window_size: choice(60, 120)
