
# 例: config/hparams/elasticnet_base.yaml
alpha: 0.001
l1_ratio: 0.5
fit_intercept: true
max_iter: 3000
tol: 0.0001
selection: cyclic
random_state: 42
positive: false
warm_start: false

# train.py 側との互換パラメータ
use_time_decay: false
time_decay_rate: 0.9999
