# config/hparams/lgbm_default.yaml
objective: "regression"
metric: "rmse"
boosting_type: "gbdt"
n_jobs: -1
random_state: 42
learning_rate: 0.01
num_leaves: 31
max_depth: 8
min_child_samples: 100
subsample: 0.8
colsample_bytree: 0.5
use_time_decay: false
n_estimators: 10000