# config/hparams/lgbm_default.yaml
objective: "regression"
metric: "rmse"
boosting_type: "gbdt"
n_jobs: -1
random_state: 42
learning_rate: 0.05
num_leaves: 31
max_depth: 8
min_child_samples: 100
bagging_fraction: 0.8
feature_fraction: 0.5
lambda_l1: 0.001
lambda_l2: 6.423
is_unbalance: true
use_time_decay: true
time_decay_rate: 0.9999
bagging_freq: 6
verbose: 1