
name: "str_triple_barrier"
column: "target_str_triple_barrier"   # データセット内のどの列をターゲットにするか
task_type: "multiclass"        # 回帰(continuous)か分類(binary/multiclass)か
prediction_horizon: 60       # 何日先を予測するか（5日後など）