variant_global: "v1_stable"

promotions:
  - model: lgbm
    domain: tac
    role: alpha_gr
    study: "final_sweep_lgbm_tac_alpha_gr_20260509_212938"
    enabled: false

  - model: lgbm
    domain: str
    role: alpha
    study: "final_sweep_lgbm_str_alpha_20260522_092932"
    enabled: false

  - model: gandalf
    domain: tac
    role: alpha_gr
    study: "final_sweep_gandalf_tac_alpha_gr_20260524_141241"
    enabled: true